### ISSUE TITLE
Section links not styled

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5170] opened 2023-06-24 05:04 UTC
I'm working on Panel 1.1.1 with the the Streamlit. When I look at my app the most eye catching is the big, not styled section link. Please make it invisible when not hovered upon. Thanks.

![image](https://github.com/holoviz/panel/assets/42288570/d4394f50-7f0f-42ea-a4cb-b24eeb89a8e9)

```python
import random

import panel as pn
pn.extension(sizing_mode="stretch_width")


def create_row(_):
    value = random.randint(0, 100)
    row = pn.widgets.TextInput(name="Enter a number", value=str(value))
    rows.append(row)

rows = pn.Column()
add_row = pn.widgets.Button(name="Add new row", on_click=create_row)
clear_rows = pn.widgets.Button(name="Clear all rows", on_click=lambda _: rows.clear())
main = pn.Column("# Dynamically add new rows", pn.Row(add_row, clear_rows), rows)

pn.template.BootstrapTemplate(main=[main], main_max_width="max(50%, 600px)").servable()
```

**Comment by MarcSkovMadsen** [comment] 2023-06-24 05:50
A second issues is the margin of the title. I would recommend adding some margin to the "Panel Application" title. But remember to check that it works when the `site` parameter is set too.

**Comment by philippjfr** [comment] 2023-06-24 11:36
That indeed looks like a bunch of CSS is missing. Can you see in your browser console if anything failed to load?

**Comment by philippjfr** [comment] 2023-06-28 13:24
Closing due to no reply and the fact that I cannot reproduce.

**Closed by philippjfr** 2023-06-28 13:24 UTC
Labels: type: enhancement
