### ISSUE TITLE
Tooltip of HoloViews Chart is doubled when using pn.panel

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3713] opened 2022-07-23 07:41 UTC
panel==0.13.1

```python
import pandas as pd

import holoviews as hv

hv.extension('bokeh')

station_info = pd.read_csv('https://raw.githubusercontent.com/holoviz/holoviews/master/examples/assets/station_info.csv')
scatter = hv.Scatter(station_info, kdims='services', vdims='ridership')
scatter.opts(tools=['hover'])

import panel as pn
pn.panel(scatter, sizing_mode="stretch_both").servable()
```

![image](https://user-images.githubusercontent.com/42288570/180595677-3bd667fa-fa01-4e73-b493-2464bd5cbdcd.png)

I would expect to see the `services` and `ridership` only once in the tooltip.

Please note if I use the `pn.pane.HoloViews` pane the tooltip is not doubled.

**Comment by Hoxbro** [comment] 2023-12-05 21:37
I think this is expected behavior as there is two identical values for this point. This is easier to see with hvplot: `station_info.hvplot.scatter(x='services', y='ridership', hover_cols="all")`

![image](https://github.com/holoviz/panel/assets/19758978/e0d98611-5739-4400-9d39-24d49b593421)

I see the double point also with `pn.pane.HoloViews` but I don't know if that just because a lot of time has passed since the original issue.  

I will close the issue, please reopen if you still think there is a bug.

**Closed by Hoxbro** 2023-12-05 21:37 UTC
Labels: type: bug
