### ISSUE TITLE
Auto determine and configure the environment

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2242] opened 2021-04-24 12:29 UTC
If you go to https://github.com/holoviz/panel you can see that Panel can be used in many different environments: Notebook, Lab, VS Code, Colab, Panel Server, Voila Server etc.

I am switching back and forth between most of these. Especially Jupyter Labs, Notebook running in VS Code, Panel Server and now potentially Voila Server. C.f. https://github.com/holoviz/panel/issues/2241

Right now I have to add/ remove `pn.extension(comms='vscode')`, `pn.extension(comms='colab')`, `pn.extension(comms='ipywidgets')` depending on the environment. 

It is not efficient that I have to change/ update the code depending on the development or deployment environment. Furthermore it can confuse new users and lead to support questions on how to use Panel in XYZ environment. Or just users leaving because they don't think it works in their favorite environment. Furthermore it makes it complicated to develop example notebooks for a community of users with different preferences for using those example notebooks. For example for Panel or for work.

## Solution

Find a way to auto detect the environment and automatically do the configuration.

**Comment by MarcSkovMadsen** [comment] 2021-04-24 13:01
I've asked the VS-Code Python developers if there is a way to determine if I am running inside VS Code Interactive Notebook.

https://github.com/microsoft/vscode-python/discussions/16034

**Comment by philippjfr** [comment] 2021-04-24 14:46
We have asked Jupyter again and again whether there is some way to determine the frontend and the answer each time was that the backend should stay completely agnostic as to the frontend and therefore no support for identifying the environment would **ever** be provided. So while I agree this would be nice I'm strongly inclined to close this issue since it is out of our hands and anything we do implement will be hacky and/or very brittle.

**Comment by jbednar** [comment] 2021-04-24 15:47
What if we provided `pn.extension('auto')`, and explicitly documented that `'auto'` may be useful but it is hacky and  completely unsupported and we recommend specifying a specific extension instead?

**Comment by MarcSkovMadsen** [comment] 2021-04-24 15:53
Thanks @philippjfr . I feel your frustration.

If ever they (Jupyter, VS Code, Colab etc) should provide something. What should it be? An imported module?

**Comment by MarcSkovMadsen** [comment] 2021-04-24 15:55
The goal is not to need to specify `pn.extension()` as it is not needed on the server unless with specifically need to import and extension. The code needs to be the same across environments. Otherwise the promise of Panel of going from exploration to production with the same code base does not hold in practice.

**Comment by philippjfr** [comment] 2021-04-24 16:37
>What if we provided pn.extension('auto'), and explicitly documented that 'auto' may be useful but it is hacky and completely unsupported and we recommend specifying a specific extension instead?

That supposes we have a mechanism (hacky or not) to detect the frontend, which we don't.

>The goal is not to need to specify pn.extension() as it is not needed on the server unless we specifically need to import an extension.

Panel itself (and Bokeh) is the extension that has to be loaded in the notebook, so there's no way around it and since running the extension on the server isn't harmful it should generally be included.

**Comment by jbednar** [comment] 2021-04-24 16:38
Using the same code is already possible between server and notebook contexts; `pn.extension('bokeh')` should work in both cases. It's all the other contexts (`'ipywidgets'`, `'vscode'`, etc.) that currently have to be specified explicitly.

In any case, the code to install the javascript that's required in some environments has to be invoked _somehow_, and so if not through a call to `pn.extension()` or some similar method, it would have to be done automatically on import.  `hvPlot` is an example of using a module in this way, e.g. `import hvplot.pandas` implicitly calls the equivalent of `panel.extension('bokeh')`. But even in hvPlot, importing `hvplot` alone doesn't do this, because otherwise there would be no way to avoid executing this sometimes brittle code, and I think the same would be true of Panel. I.e., even if auto-detection code were available, you'd still need to do a special import like `import panel.auto` to invoke that code, so that the library itself would behave politely and not try to mess with stuff as this auto code would do.

So such a request comes down to (1) accepting that invoking the auto-detection would still need to be done explicitly, and (2) actually implementing the autodetection.  If you're ok with (1), seems like it would be ok to try to achieve (2), though it is not at all straightforward (by design of Jupyter).

**Comment by philippjfr** [comment] 2021-04-24 16:40
To be clear `pn.extension('bokeh')` is not something that exists, you're thinking of `hv.extension` where the arguments load the plotting backend. For `pn.extension` the arguments load optional libraries like deck.gl, MathJax, echarts, vega etc.

**Comment by jbednar** [comment] 2021-04-24 16:48
Good point; I was confusing about that. But here we are not talking about deck/echart/vega/mathjax support, but about environments: vscode, collab, jupyter, jupyterlab, bokeh server, voila.

**Comment by MarcSkovMadsen** [comment] 2021-04-27 05:02
For VS Code running locally on a laptop `VSCODE_PID` is injected into the kernel. My estimate is that it would catch +90% of VS Code use cases.

![image](https://user-images.githubusercontent.com/42288570/116187719-4e594080-a726-11eb-8f2b-43131ba4e9af.png)

Would you accept a PR that sets `comms=`vscode` if `VSCODE_PID` is set @philippjfr ?

**Comment by MarcSkovMadsen** [comment] 2021-04-27 05:06
And for Google Colab something similar could probably be done. For example based on whether `COLAB_GPU` is set or not?

![image](https://user-images.githubusercontent.com/42288570/116188130-23bbb780-a727-11eb-8e43-83bb36591bf1.png)

**Comment by MarcSkovMadsen** [comment] 2022-01-15 04:33
I believe the only one outstanding is `colab`. Would be really great to get supported such that Sophia, I and other blogstars 😄 can communicate easily.

We would like to get rid of the explanations

![image](https://user-images.githubusercontent.com/42288570/149608938-bd2baf12-17d1-4555-a720-955de8828790.png)

and support on discourse when users ask about this.

**Comment by philippjfr** [comment] 2022-01-17 12:42
We already auto-determine colab here: https://github.com/holoviz/panel/blob/master/panel/config.py#L556

**Comment by jbednar** [comment] 2022-01-18 20:43
Sounds like the docs need updating?

**Comment by MarcSkovMadsen** [comment] 2022-01-19 04:23
https://github.com/holoviz/panel#google-colab

![image](https://user-images.githubusercontent.com/42288570/150063762-abe95349-aee4-45e6-bd33-03f8118f5934.png)

**Comment by jbednar** [comment] 2022-01-19 19:58
I'm pretty sure that I wrote that and then Philipp made it obsolete. PRs to update the docs strongly encouraged!

**Comment by philippjfr** [comment] 2023-05-03 00:36
I think we now auto-detect all common environments and docs have been updated.

**Closed by philippjfr** 2023-05-03 00:36 UTC
Labels: type: feature
