### ISSUE TITLE
Sizing the Player widget

### ISSUE THREAD

**Issue by Tchaklaka** [holoviz/panel#1110] opened 2020-02-20 11:57 UTC
Hello, trying to resize the Player widget to fill the available size gives a weird behaviour. I tried every possibility thanks to the control panel: changing absolute/relative width, margins...

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

Python 3.7.3
Bokeh 1.4.0
Holoviews 1.12.7
Tornado 6.0.3
Panel 0.8.0
Firefox 60.9.0esr
Windows 10

#### Description of expected behavior and the observed behavior

Expected behavior: Increasing the width makes the slider and the control buttons wider, while each component remains centered versus the other.
Observed behavior: Increasing the width makes the control buttons go right, the slider keeps its position and neither are resized.

#### Complete, minimal, self-contained example code that reproduces the issue

```
player = pn.widgets.Player(name='player', start=0, end=100, value=32, loop_policy='loop')
control = player.controls(jslink=True)

```

#### Stack traceback and/or browser JavaScript console output

```
[bokeh] Lost websocket 0 connection, 1001 ()                                                 bokeh.min.js:608:4532
[bokeh] Websocket connection 0 disconnected, will not attempt to reconnect  bokeh.min.js:608:2120
[bokeh] setting log level to: 'info'                                                                     bokeh.min.js:317:2249
[bokeh] Websocket connection 0 is now open                                                  bokeh.min.js:608:3985
[bokeh] document idle at 1244 ms                                                                  bokeh.min.js:242:1536
Bokeh items were rendered successfully                                                           bokeh.min.js:240:902
```

#### Screenshots or screencasts of the bug in action

![image](https://user-images.githubusercontent.com/53322938/74931021-1ac2ae00-53df-11ea-83d6-6e6841c5e38c.png)

**Comment by xavArtley** [comment] 2020-02-22 07:40
Dupe of #538

**Closed** 2020-05-19 10:36 UTC
Labels: type: bug
