### ISSUE TITLE
Repr of Tabulator freezes chrome tab

### ISSUE THREAD

**Issue by Melendowski** [holoviz/panel#3001] opened 2021-12-09 14:18 UTC
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

#### Description of expected behavior and the observed behavior
When trying to view a decent sized numerical array with `Tabulator`  widget in a `Tabs` layout, the `repr` generation causes the notebook/chrome-tab to become unresponsive. 

Using `Anaconda3-2021.05-Windows-x86_64 ` with base environment 

Versions of imported modules

panel=0.12.1
pandas=1.2.4
numpy=1.20.1
python=3.8.8
chrome=96.0.4664.93
jupyter=1.0.0
jupyter-packaging=0.7.12
jupyter_client=6.1.12
jupyter_console=6.4.0
jupyter_core=4.7.1
jupyter_server=1.4.1
jupyterlab=3.0.14
jupyterlab_pygments=0.1.2
jupyterlab_server=2.4.0
jupyterlab_widgets=1.0.0

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks
import numpy as np
import pandas as pd
from panel.widgets import DataFrame, Tabulator
from panel import Tabs

df = pd.DataFrame(np.random.randn(10000))

dataframe_viewer = Tabs(dynamic=True, closable=True)
tabulator_viewer = Tabs(dynamic=True, closable=True)

dataframe_viewer.append(DataFrame(df))
dataframe_viewer

tabulator_viewer.append(Tabulator(df))

tabulator_viewer
```
[Gist to notebook example](https://gist.github.com/Melendowski/9219505c8afc0cd42805cfafa77e8e2e)

#### Stack traceback and/or browser JavaScript console output
None just freezes

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/36213781/145411086-1d381d62-3e78-4c53-b847-b6deb84bd139.png)

**Comment by philippjfr** [comment] 2021-12-09 14:56
Thanks, this is effectively a duplicate of https://github.com/holoviz/panel/issues/2841 so I'll close.

**Closed by philippjfr** 2021-12-09 14:56 UTC
