### ISSUE TITLE
LaTeX in Markdown not working unless you provide raw strings

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4376] opened 2023-02-01 13:42 UTC
I'm on Panel 0.14.3.

A colleague of mine wanted to start including LaTeX in his app. He was using the Markdown pane as is should support LaTeX. He could not get it working. After some initial confusion we figured out its because the markdown string provided needs to be a raw string.

This was quite confusing as the documentation did not make that clear. Please make this clear.

https://panel.holoviz.org/reference/panes/Markdown.html

![image](https://user-images.githubusercontent.com/42288570/216058720-7e45a78c-308d-4341-88cb-041c47dbc577.png)

## Reproducible Example

```python
import panel as pn

pn.extension("mathjax")

pn.pane.Markdown("$$\frac{1}{n}$$")
pn.pane.Markdown(r"$$\frac{1}{n}$$")
```

![image](https://user-images.githubusercontent.com/42288570/216059089-7704f652-9aca-41cf-b253-97f57cd9fba4.png)

**Comment by philippjfr** [comment] 2023-02-01 13:46
Duplicate of https://github.com/holoviz/panel/issues/3792

**Comment by philippjfr** [comment] 2023-02-01 13:47
Actually not the same issue. Will reopen.

**Closed** 2023-02-04 23:37 UTC
Labels: type: enhancement, type: docs
