### ISSUE TITLE
Different app reactivity between .show, .servable and bokeh serve 

### ISSUE THREAD

**Issue by fmaussion** [holoviz/panel#778] opened 2019-11-13 22:01 UTC
We have an app (https://github.com/pat-schmitt/glacier_simulator) which works as follows: when the user presses the "run the model" button, a relatively expensive numerical model runs in the background. In a loop, we report back at each model time step and use `.event()` to update the figure, so that the user sees the glacier grow. 

The expected behavior looks like this:

![servable](https://user-images.githubusercontent.com/10050469/68807546-490a5200-0668-11ea-9e27-61fce051b9f9.gif)

and **this is what we get when running the app locally with `.servable()` or (strangely enough), when running the app via mybinder using `panelserverextension.py`** (which uses `panel serve` internally?)
 
However, when we run the app locally with `.show()` or when we serve the app on google cloud using `bokeh serve`, the app now doesn't update during the simulation but updates all frames at the end of the simulation, looking like this:

![show](https://user-images.githubusercontent.com/10050469/68807922-08f79f00-0669-11ea-8610-2a3005a8ab2f.gif)

If you want to see the app running, just click "run the model" and you can compare them depending on how we serve them:
-  mybinder: https://mybinder.org/v2/gh/pat-schmitt/glacier_simulator/master?urlpath=/proxy/5006/simulator
- google cloud: https://bokeh.oggm.org/simulator/simulator

Obviously, we would expect our own server to be faster and slicker than mybinder, but because of this glitch this is not the case. Where do these differences come from? Why is `.show()` different than `.servable()` locally? Thanks for any hint!

cc @pat-schmitt who wrote the app and @TimoRoth who maintains the server

**Comment by philippjfr** [comment] 2019-11-13 22:09
@fmaussion Could you report all versions? I'm particularly interested in the version of param in this case.

**Comment by fmaussion** [comment] 2019-11-13 23:23
Sorry I don't have access to this info right now. @pat-schmitt and @TimoRoth will report tomorrow. 

Regarding `panel serve`: is this any different than `bokeh serve`, and would you recommend to use `panel serve` on our server?

**Comment by TimoRoth** [comment] 2019-11-13 23:36
You can run the app in the exact same fashion it's running on bokeh.oggm.org via the following:
```
docker run -e BOKEH_ALLOW_WS_ORIGIN=127.0.0.1 -p 8080:8080 oggm/bokeh:20191108 git+https://github.com/pat-schmitt/glacier_simulator.git simulator.ipynb
```

It's on 127.0.0.1:8080 afterwards.

pip freeze output for the packages in that container:

<details>
  <summary>Click to expand!</summary>

```
affine==2.3.0
atomicwrites==1.3.0
attrs==19.3.0
backcall==0.1.0
bleach==3.1.0
bokeh==1.4.0
Cartopy==0.17.0
certifi==2019.9.11
cftime==1.0.4.2
chardet==3.0.4
Click==7.0
click-plugins==1.1.1
cligj==0.5.0
cloudpickle==1.2.2
colorcet==2.0.2
configobj==5.0.6
coverage==4.5.4
cycler==0.10.0
Cython==0.29.14
dask==2.6.0
datashader==0.8.0
datashape==0.5.2
decorator==4.4.1
defusedxml==0.6.0
descartes==1.1.0
distributed==2.6.0
entrypoints==0.3
filelock==3.0.12
Fiona==1.8.9.post2
fsspec==0.5.2
GDAL==2.4.3
geopandas==0.6.1
geoviews==1.6.5
HeapDict==1.0.1
holoviews==1.12.6
hvplot==0.5.2
idna==2.8
ilock==1.0.2
imageio==2.6.1
importlib-metadata==0.23
ipykernel==5.1.3
ipython==7.9.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.1
Jinja2==2.10.3
joblib==0.14.0
jsonschema==3.1.1
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.1
kiwisolver==1.1.0
llvmlite==0.30.0
locket==0.2.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.0.3
mistune==0.8.4
more-itertools==7.2.0
motionless==1.3.2
msgpack==0.6.2
multipledispatch==0.6.0
munch==2.5.0
nbconvert==5.6.1
nbformat==4.4.0
netCDF4==1.5.3
networkx==2.4
nose==1.3.7
notebook==6.0.2
numba==0.46.0
numexpr==2.7.0
numpy==1.16.5
oggm==1.1.3.dev22+g28741f0
packaging==19.2
pandas==0.25.3
pandocfilters==1.4.2
panel==0.6.4
param==1.9.2
parso==0.5.1
partd==1.0.0
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.2.1
pluggy==0.13.0
portalocker==1.5.1
progressbar2==3.47.0
prometheus-client==0.7.1
prompt-toolkit==2.0.10
psutil==5.6.5
ptyprocess==0.6.0
py==1.8.0
pyct==0.4.6
Pygments==2.4.2
pyparsing==2.4.4
pyproj==2.4.1
pyrsistent==0.15.5
pyshp==2.1.0
pytest==5.2.2
pytest-cov==2.8.1
pytest-mpl===0.111.oggm
python-dateutil==2.8.1
python-utils==2.3.0
pytz==2019.3
pyviz-comms==0.7.2
PyWavelets==1.1.1
PyYAML==5.1.2
pyzmq==18.1.0
qtconsole==4.5.5
rasterio==1.1.0
requests==2.22.0
salem===0.2.4-9-g6b63c4e
scikit-image==0.16.2
scipy==1.3.1
Send2Trash==1.5.0
Shapely==1.6.4.post2
six==1.13.0
snuggs==1.4.7
sortedcontainers==2.1.0
tables==3.6.1
tblib==1.5.0
terminado==0.8.2
testpath==0.4.4
tifffile==2019.7.26
toolz==0.10.0
tornado==6.0.3
traitlets==4.3.3
urllib3==1.25.6
versioneer==0.18
virtualenv==16.7.7
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.5.1
xarray==0.14.0+44.g4dce93f1
zict==1.0.0
zipp==0.6.0
```

</details>

**Comment by philippjfr** [comment] 2019-11-13 23:50
Thanks for the detailed info! I hope we can squeeze a fix into 0.7 due to be released tomorrow.

**Comment by philippjfr** [comment] 2019-11-25 23:54
There is in effect no difference between bokeh serve and panel serve so I cannot explain this and cannot reproduce it either. The only situation where I can reproduce it is using `.show`. This simple example exhibits the same behavior

```python
import time
import panel as pn
pn.extension()

button = pn.widgets.Button(name='Run')
row = pn.Row(button)

def button_click(event, count=5):
    time.sleep(1)
    row.append(1)
    if count-1 > 0:
      button_click(None, count-1)
    
button.on_click(button_click)
row.show()
```

**Comment by pat-schmitt** [comment] 2019-11-26 11:33
I just found a possible solution in the [bokeh documentation](https://docs.bokeh.org/en/latest/docs/user_guide/server.html#updating-from-threads). I think the problem is that bokeh locks the document until all computation is finished and afterwards update the document. So i have modified the simple example of @philippjfr 

```python
import time
import panel as pn

from threading import Thread
from tornado import gen
from functools import partial

pn.extension()

button = pn.widgets.Button(name='Run')
row = pn.Row(button)


@gen.coroutine
def update(number=1):
    row.append(number)


def blocking_task():
    for i in range(5):
        time.sleep(1)
        # update the document from callback
        doc.add_next_tick_callback(partial(update, number=i))


def button_click(event):
    global doc
    # get the current bokeh document
    doc = pn.state.curdoc
    # start the computation in an new thread
    thread = Thread(target=blocking_task)
    thread.start()


button.on_click(button_click)
row.show()
``` 
This solution only works when a bokeh server is running (in a jupyter notebook you must use `.app('localhost:8888')` to directly see if the app is working or `.show()` to display the app in a new browser tab and when you are finished you can use `.servable()` again). Hopefully it will also work with the glacier simulator :)

**Comment by xavArtley** [comment] 2019-11-27 17:44
By slighting modifiying your code we can make it works in notebook too (at least for the `append row`):
Just need to test if doc is `None` or not.
However I added a StaticText widget, this one is not updating in notebook but it works in bokeh server
```
import time
import panel as pn

from threading import Thread
import asyncio
from functools import partial

pn.extension()

button = pn.widgets.Button(name='Run')
text = pn.widgets.StaticText(value='-1')
row = pn.Row(button)


@asyncio.coroutine
def update(number=1):
    row.append(number)
    text.value = str(number)

def blocking_task(doc):
    for i in range(5):
        time.sleep(1)
        # update the document from callback
        if doc:
            doc.add_next_tick_callback(partial(update, number=i))
        else:
            row.append(i)
        

def button_click(event):
    thread = Thread(target=partial(blocking_task, doc=pn.state.curdoc))
    thread.start()

button.on_click(button_click)
pn.Column(row, text)
```

**Comment by philippjfr** [comment] 2019-12-08 02:44
Okay, I've figured out a way to execute the events synchronously. I'm a little worried about issues with appropriate locking so I might add an experimental `unlock` utility which you could use like this:

```python
def button_click(doc):
    for i in range(5):
        time.sleep(1)
        with unlock():
            text.value = str(number)

button.on_click(button_click)
```

This approach works in my tests and doesn't have to create a separate thread. Maybe given a deeper understanding of the locking mechanisms we could even enable it by default in some scenarios but for now I'm more comfortable adding it as an experimental feature.

**Comment by philippjfr** [comment] 2019-12-08 03:03
Could someone try out: https://github.com/holoviz/panel/pull/857

I did enable it by default now but am still not sure how safe it is to do that.

**Comment by pat-schmitt** [comment] 2019-12-09 17:34
With only panel elements the unlock mechanism works fine for me. 
I also tested it together with a HoloViews Dynamic Map. For this i imported the `unlocked()` function from `panel.io` and used it with the Dynamic Map `.event()`. I found that it is only working when the data, given to the HoloViews curve, is of type `int64`. To make it clear here a small example:

```python
import panel as pn
import holoviews as hv
from holoviews.streams import Stream, param
import time
import numpy as np

from panel.io import unlocked

pn.extension()
hv.extension('bokeh', width=100)

# define data and curve
data_type = 'int64'
x_curve = np.array([0, 1], dtype=data_type)
y_curve = np.array([0, 10], dtype=data_type)

def set_output_curve():
    global output_curve
    output_curve = hv.Curve((x_curve, y_curve),
                            'x_label',
                            'y_label')

set_output_curve()

# define dynamic map
dmap_change_flag = True

def dmap_function(change=True):
    return output_curve

dmap_stream = Stream.define('dmap_stream', change=True)
dmap = hv.DynamicMap(dmap_function, streams=[dmap_stream()])


# function for simulating model run
def run_the_model():
    global y_curve
    global dmap_change_flag

    for i in range(10):
        # simulate model calculation
        time.sleep(1)
        y_curve[-1] = y_curve[-1] - 1

        # set the new curve
        set_output_curve()

        # force the dynamic map to change
        with unlocked():
            dmap.event(change=dmap_change_flag)
        dmap_change_flag = not dmap_change_flag


# define button
button = pn.widgets.Button(name='start')

def start_button_click(event):
    run_the_model()

button.on_click(start_button_click)


pn.Column(button, dmap).show()
```
When you change `data_type = 'float64'` the unlock is not working and also the final output is not as expected (after some time the curve from the second loop iteration is shown).

**Comment by philippjfr** [comment] 2019-12-09 18:03
That's really bizarre, the actual event does get sent as expected it just doesn't seem to update client side.

**Comment by philippjfr** [comment] 2019-12-09 18:05
Ah, I get it now, there appears to be some issue sending binary buffers. I can probably fix that.

**Comment by philippjfr** [comment] 2019-12-09 18:14
@pat-schmitt Thanks for finding that, I've now pushed a fix which resolved that. Ideally we'd also do the unlocking in HoloViews so you don't have to do it manually at all.

**Closed** 2019-12-10 16:11 UTC
Labels: type: bug

**Comment by fmaussion** [comment] 2019-12-10 16:17
Thanks so much @philippjfr and @pat-schmitt for the prompt and efficient reactions here.

> Ideally we'd also do the unlocking in HoloViews so you don't have to do it manually at all 

Is there an issue / PR on holoviz we can follow? We are now waiting for a panel / holoviews release before we publish the app.

**Comment by philippjfr** [comment] 2019-12-10 16:21
Btw it's been pointed out to me that this regression happened when updating to tornado 6.x (see #860) so for now you might be able to pin "tornado<6" and have it work.

**Comment by fmaussion** [comment] 2019-12-10 16:24
>  for now you might be able to pin "tornado<6" and have it work.

ha! Awesome, thanks

**Comment by pat-schmitt** [comment] 2020-04-09 06:36
@philippjfr I want to let you know that the unlock mechanism is not working by default with the new versions of panel and holoviews, but it does with the solution presented here. I am not sure if you have planed to make it as default or not.

**Comment by philippjfr** [comment] 2020-04-09 10:36
Could you open a new issue with an example where this doesn't work?

**Comment by philippjfr** [comment] 2020-04-09 10:37
We've had to make some changes to the way unlocking works because it was not quite safe, which can potentially disable it in certain cases.

**Comment by DSDEV27001** [comment] 2021-04-19 11:40
@pat-schmitt @philippjfr @MarcSkovMadsen I am looking to do something similar to this but using a JS call which is currently tied to an on_click event. Is this achievable?

**Comment by philippjfr** [comment] 2021-04-19 12:12
@DSDEV27001 would suggest posting to the discourse with some more details.
