### ISSUE TITLE
Plotly Figure cannot dynamically be added and removed. HoloViews can.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#840] opened 2019-12-04 04:22 UTC
#### System Info

- Panel: 0.7.0
- Bokeh: 1.4.0
- Python: 3.7.4
- OS: Windows 8.1
- Browser: Chrome

#### Description of expected behavior and the observed behavior

I'm trying to use Plotly plots in a multi page app using Panel. The app consists of multiple pages that the user can navigate to via buttons. 

- When the user navigates to the "Plotly" page he just sees blank where he should see a Plotly Figure. 
- If the user navigates to a very similar "Holoviews" page he sees the "Holoviews" figure.

I would have expected the user to be able to navigate to and see the Plotly Figure.

![navigation_to_plotly_not_working](https://user-images.githubusercontent.com/42288570/70112487-d03e5a80-1655-11ea-8fea-d10cb217a6b5.gif)

#### Complete, minimal, self-contained example code that reproduces the issue

```
import holoviews as hv
import hvplot.pandas
import pandas as pd
import panel as pn
import param
from plotly import express as px

pn.extension()


def navigation_button(page, page_outlet):
    button = pn.widgets.Button(name=page.name)

    def navigate_to_page(event):
        page_outlet.clear()
        page_outlet.append(page)

    button.on_click(navigate_to_page)
    return button


def get_chart_data():
    chart_data = {
        "Day": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",],
        "Orders": [15539, 21345, 18483, 24003, 23489, 24092, 12034],
    }
    return pd.DataFrame(chart_data)


def holoviews_fig():
    data = get_chart_data()
    line_plot = data.hvplot.line(
        x="Day", y="Orders", width=None, line_color="#007BFF", line_width=6,
    )
    scatter_plot = data.hvplot.scatter(x="Day", y="Orders", width=None).opts(
        marker="o", size=10, color="#007BFF"
    )
    fig = line_plot * scatter_plot
    gridstyle = {"grid_line_color": "black", "grid_line_width": 0.1}
    fig.height = 500
    fig = fig.opts(
        responsive=True,
        toolbar=None,
        yticks=list(range(12000, 26000, 2000)),
        ylim=(12000, 26000),
        gridstyle=gridstyle,
        show_grid=True,
    )
    return fig


def holoviews_page() -> pn.Column:
    fig = holoviews_fig()
    return pn.Column(
        pn.pane.Markdown("# Holoviews"), fig, name="Holoviews", sizing_mode="stretch_both",
    )


def plotly_fig():
    fig = px.line(get_chart_data(), x="Day", y="Orders")
    fig.update_traces(mode="lines+markers", marker=dict(size=10), line=dict(width=4))
    fig.layout.paper_bgcolor = "rgba(0,0,0,0)"
    fig.layout.plot_bgcolor = "rgba(0,0,0,0)"
    fig.layout.width = 1000
    return fig


def plotly_page(*args, **kwargs) -> pn.Column:
    fig = plotly_fig()
    return pn.Column(pn.pane.Markdown("# Plotly"), fig, name="Plotly", sizing_mode="stretch_both",)


def main():
    issue = """# Issue

I can't see any difference in the Panel specific implementation of the Plotly and Holoviews pages.
Still only the Holoviews page shows! The Plotly page does not!"""
    home = pn.pane.Markdown(issue, name="Issue")
    holoviews = holoviews_page()
    plotly = plotly_page()

    page_outlet = pn.Column(home, sizing_mode="stretch_both")
    sidebar = pn.Column(
        navigation_button(home, page_outlet),
        navigation_button(plotly, page_outlet),
        navigation_button(holoviews, page_outlet),
        pn.layout.HSpacer(),
        width=300,
        sizing_mode="stretch_height",
        background="lightgray",
    )
    app = pn.Row(sidebar, page_outlet, sizing_mode="stretch_both")
    return app


if __name__.startswith("bk"):
    main().servable("issue")
    # plotly_page().servable("plotly_page stand alone works!")
```

**Comment by philippjfr** [comment] 2019-12-05 00:15
This works for me if the Plotly extension is loaded explicitly:

```
pn.extension('plotly')
```

I thought that was only required for notebook support so it looks like there may have been a regression.

**Comment by philippjfr** [comment] 2019-12-05 00:16
Importing the plotly model also seems to be sufficient:

```python
import panel.models.plotly
```

**Comment by philippjfr** [comment] 2019-12-05 00:18
The issue is that when the model is first served the Plotly model isn't included, as I understand it in bokeh 2.0 resources can be loaded dynamically which would address the issue.

**Comment by MarcSkovMadsen** [comment] 2019-12-05 03:36
I can confirm that the suggestions work. Thanks.

If possible loading the plotly extension should automatically be done as soon as the user includes a Plotly pane. Alternatively it should be very clear in the documentation that the plotly extension needs to be loaded. All this just to lower the friction of using Panel.

**Comment by philippjfr** [comment] 2019-12-05 03:40
>If possible loading the plotly extension should automatically be done as soon as the user includes a Plotly pane.

Since the pane is defined in a function which isn't called until after the app has been initialized it has no way of knowing that it is included. The next bokeh release will fix this, so I don't think there's much to do in panel itself except to update this text in the Plotly reference notebook and docstring.

**Comment by philippjfr** [comment] 2019-12-05 03:41
Note the same will be true for all external dependencies including vega, MathJax/KaTeX, Vtk and Ace.

**Comment by MarcSkovMadsen** [comment] 2019-12-05 03:42
So a general note somewhere on dynamically using external dependencies needs explicitly loading them via pn.config.extension('xyz') would be nice.

**Comment by jbednar** [comment] 2019-12-05 04:13
A PR adding such a note at the spot you'd have noticed it in the docs would be greatly appreciated!

**Comment by philippjfr** [comment] 2021-06-29 08:28
Closing, you have to load extensions, this is documented. If one day Bokeh somehow let's us actually load dependencies dynamically that will be nice but until then this is expected behavior.

**Closed by philippjfr** 2021-06-29 08:28 UTC
Labels: type: bug
