### ISSUE TITLE
New widget combining Multichoice and AutocompleteInput

### ISSUE THREAD

**Issue by paoloalba** [holoviz/panel#6870] opened 2024-05-28 17:33 UTC
I would like to allow arbitrary text into Multichoice, along with the given option. I.e. the user is able to introduce new elements (which however do not enter the options list) always of the same type.

In the end I would like to have maybe an extension of AutocompleteInput into a list. IPywidgets already implement it rather well: https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#tag-widgets

Alternatively one could extend LiteralInput of list type, where the type of each entered element of the list is validated (pure string, float, int).

**Comment by ahuang11** [comment] 2024-05-28 18:15
I think this could be a duplicate of https://github.com/holoviz/panel/issues/5047

At the moment, I think you could theoretically use https://panel.holoviz.org/reference/widgets/JSONEditor.html to add to a list

**Comment by paoloalba** [comment] 2024-06-01 07:20
it seems indeed a duplicate. I see that the feature as been postponed constantly since version 1.2.0 . Any reason about that? Difficult to implement? Incompatible with the current model? Lack of demand? I see that there was another duplicate of it.

**Comment by philippjfr** [comment] 2024-06-27 22:16
> it seems indeed a duplicate. I see that the feature as been postponed constantly since version 1.2.0 . Any reason about that? Difficult to implement? Incompatible with the current model? Lack of demand? I see that there was another duplicate of it.

Simply lack of developer time combined with lack of demand, always happy to see user contributions though.

**Closed by philippjfr** 2024-06-27 22:16 UTC
