### ISSUE TITLE
panel.Param does not support changing objects of ObjectSelector dynamically

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1461] opened 2020-07-02 05:28 UTC
Panel: 0.9.5
bokeh: 2.0.2

I was trying to help a user on Discourse here https://discourse.holoviz.org/t/based-on-a-select-widget-update-a-second-select-widget-then-how-to-link-the-latter-to-a-reactive-plot/917.

I could develop an answer to his question but I believe there is a bug. I had to implement a hack/ work around to get it working.

```Code
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
import colorcet as cc
import panel as pn
import param

COLLECTIONS = ["matplotlib", "colorcet"]

MATPLOTLIB_COLORMAPS = sorted(
    [
        "viridis",
        "plasma",
    ],
    key=str.casefold,
)

COLORSET_COLORMAPS = sorted(
    [
        "bgy",
        "bkr",
        "bgyw",
    ]
)
COLOR_MAPS = {"matplotlib": MATPLOTLIB_COLORMAPS, "colorcet": COLORSET_COLORMAPS}


class ColorApp(param.Parameterized):
    collection = param.ObjectSelector(default="matplotlib", objects=COLLECTIONS)
    color_map = param.ObjectSelector(default="viridis", objects=MATPLOTLIB_COLORMAPS)
    use_hack = param.Boolean(default=False)

    settings_pane = param.Parameter()
    plot_pane = param.Parameter()
    view = param.Parameter()

    def __init__(self, **params):
        params["settings_pane"] = pn.Param(
            self, parameters=["collection", "color_map", "use_hack"], show_name=False, width=300, background="grey"
        )
        params["view"] = pn.Row(sizing_mode="stretch_width")

        super().__init__(**params)

        self.view[:] = [self.settings_pane]

    @param.depends("collection", watch=True)
    def _update_color_map_parameters(self):
        print(f"update to {self.collection}")
        objects = COLOR_MAPS[self.collection]
        self.param.color_map.objects = objects

        default = objects[0]
        if self.param.color_map.default not in objects:
            self.param.color_map.default = default
        if self.color_map not in objects:
            self.color_map = default

        # hack to get drowdowns and plot to update ???
        # I should file an issue on Github
        if self.use_hack:
            self.settings_pane.object = self
            self.settings_pane.parameters = ["collection", "color_map", "use_hack"]


if __name__.startswith("bokeh"):
    ColorApp().view.servable()
else:
    ColorApp().view.show(port=5007)

```

![color_cet_hack](https://user-images.githubusercontent.com/42288570/86319732-7cb8dd00-bc35-11ea-8728-38501a4461dd.gif)

As you can see in the .gif video above the second select widget does not update in response to a change in selection of the first select widget. But if I enable the hack it does.

**Comment by MarcSkovMadsen** [comment] 2020-07-02 05:30
The hack does not work nicely as there is a glitch when the panel.Param pane updates. If there is a more efficient hack/ workaround to trigger the update, that would also help me.

**Comment by Hoxbro** [comment] 2020-07-06 11:12
Try to take a look at this:

```
import panel as pn
import param

COLLECTIONS = ["matplotlib", "colorcet"]

MATPLOTLIB_COLORMAPS = sorted(["viridis", "plasma"], key=str.casefold)

COLORSET_COLORMAPS = sorted(["bgy", "bkr", "bgyw"])
COLOR_MAPS = {"matplotlib": MATPLOTLIB_COLORMAPS, "colorcet": COLORSET_COLORMAPS}


class ColorApp(param.Parameterized):
    def __init__(self, **params):
        self.collection = pn.widgets.Select(name="Collection", options=COLLECTIONS)

        self.color_map = pn.widgets.Select(
            name="Color map", options=MATPLOTLIB_COLORMAPS
        )
        self.setting_pane = pn.Column(
            self.collection, self.color_map, width=300, background="grey",
        )

        super().__init__(**params)

    @pn.depends("collection.value", watch=True)
    def _update_color_map_parameters(self):
        print(f"update to {self.collection.value}")
        objects = COLOR_MAPS[self.collection.value]
        self.color_map.options = objects
        self.color_map.value = self.color_map.options[0]


ColorApp().setting_pane.servable()
```

**Comment by MarcSkovMadsen** [comment] 2020-07-07 13:11
I very much like focusing on the business problem, i.e. using Param to model that. And only in the end defining layout, styling and widgets.

I think it is more flexible, scales better and is more maintainable.

But maybe its just a subjective thing.

**Comment by Hoxbro** [comment] 2020-07-07 17:47
Thank you for your explanation, I will properly try to see how it works next time I do something similar. :) 

I found out you can avoid the glitch by changing the `precedence` to -1 in `param.parameters`, which always hides the parameters. 
```
settings_pane = param.Parameter(precedence=-1)
plot_pane = param.Parameter(precedence=-1)
view = param.Parameter(precedence=-1)
```
The glitch you see is because it shows all parameters and then hides them except `collection`, `color_map` and `use_hack`. With this the second line of your hack is properly not needed.

I also found that the [Google Map Viewer example](https://panel.holoviz.org/user_guide/Param.html) in the documentation seems to have the same problem. Maybe a `git bisect` could check when the example stopped working.

**Comment by MarcSkovMadsen** [comment] 2020-07-07 18:33
That’s an interesting finding @Hoxbro . I’m wondering if in general there would be a benefit for setting precedence to -1 for reactive panel components and holoviews plots I don’t expect to show via Param?

**Comment by Hoxbro** [comment] 2020-07-08 15:29
I would properly only set precedence to -1 if it is absolute needed to not create any confusion.

I have finally got the example to work without doing a hack by changing the __init__ to the following: 
```
    def __init__(self, **params):
        super().__init__(**params)
        self.settings_pane = pn.Param(
            self, parameters=["collection", "color_map", "use_hack"], show_name=False, width=300, background="grey"
        )
        self.view = pn.Row(sizing_mode="stretch_width")
        self.view[:] = [self.settings_pane]
```

**Comment by MarcSkovMadsen** [comment] 2020-07-08 19:02
@Hoxbro . So the solution is to use Param after the super init?

I think I have experienced problems before actually using Param before super init.

@philippjfr . Is there an explanation for that? Is it a bug or did I do something not supported?

**Comment by philippjfr** [comment] 2020-07-08 19:04
You should always initialize parameters via the super before doing anything with them. If you have initialized with super and it still errors it's definitely a bug though.

**Comment by itsgifnotjiff** [comment] 2023-05-06 13:02
Hmmm, I must be misunderstanding how this works. How do you wait for all the widgets to finish updating before you call the `view` function. Suppose it takes a second to update the second widget then when you update the value of the first the `view` starts updating with the initial value of the second and errors out. 

```python
class MyPanel(param.Parameterized):
    model = pnw.Select(
        name='Select Model',
        options=list(MODELS.keys()),
        value="GLOBAL_PRES_BASE_PATH"
    )
    run = pnw.Select(
        name='Select Run',
        options=MODELS_DICT[model.value]['runs']
    )
    DV_INIT_DS = fstd2nc.Buffer(
        MODELS_DICT["GLOBAL_PRES_BASE_PATH"]["fsts"][0], 
        rpnstd_metadata=True, 
        opdict=True, 
        forecast_axis=True).to_xarray()
    data_var = pnw.Select(
        name='Select Data Variable to plot',
        options=list(DV_INIT_DS.data_vars),
        value='ES'
    )
    plot = pn.pane.Str('Initial')

    @param.depends('model.value', watch=True)
    def update_runs(self):
        self.run.options = MODELS_DICT[self.model.value]['runs']

    @param.depends('model.value', 'run.value', watch=True)
    def update_data_vars(self):
        temp_ds = fstd2nc.Buffer(MODELS_DICT[self.model.value]["fsts"][0], rpnstd_metadata=True, opdict=True, forecast_axis=True).to_xarray()
        self.data_var.options = list(temp_ds.data_vars)

    @param.depends('model.value', 'run.value', 'data_var.value')
    def view(self):
        return get_hvplot(self.model.value,self.run.value,self.data_var.value)

my_panel = MyPanel()

pn.Column(
    pn.Row(my_panel.model, my_panel.run, my_panel.data_var),
    my_panel.view,
)
```

In my case run and data_var update on model.value and **then** the `view` is supposed to update once all the widgets are done. Am I using the right structure Mr. @Hoxbro? cc @philippjfr @MarcSkovMadsen

**Comment by Hoxbro** [comment] 2023-05-07 08:35
This is more of a usage question and would be better to ask on [Discourse](https://discourse.holoviz.org/).

Just by looking at it, you should **_not_** initialize widgets as class variables but inside `__init__`. Defining the widget on the class means all instances will share this widget.

If you still need guidance, try posting on Discourse with a [minimal, reproducible example (MRE)](https://stackoverflow.com/help/minimal-reproducible-example).  In general, a complete script can be copied/pasted and immediately run as-is with no modifications and without obscure third-party packages like `fstd2nc`.

**Comment by itsgifnotjiff** [comment] 2023-05-07 16:00
Thank you Mr. @Hoxbro , I was just curious if I amusing the right APIs and if there is a "Promise" based approach to `param`. Ideally I would be able to `async/await` dependencies.

**Comment by philippjfr** [comment] 2023-05-07 17:58
Let's move this discussion to Discourse if needed. I'm going to close the issue, since the original problem actually was fixed.

**Closed by philippjfr** 2023-05-07 17:58 UTC
Labels: type: docs
