### ISSUE TITLE
panel convert tries to install base64

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4045] opened 2022-10-22 03:15 UTC
panel==0.14

I'm trying to convert a demo app for awesome-panel that transforms a `VideoStream`. The `import base64` line makes the converted app try to pip install base64!

## Reproducible Example

```python
import panel as pn
import base64

pn.extension(sizing_mode="stretch_width")

pn.panel("hello").servable()
```

```bash
panel convert script2.py --to pyodide-worker --out pyodide
python3 -m http.server
```

![image](https://user-images.githubusercontent.com/42288570/197316601-68956d0f-0384-4cf2-87de-4e88ee978ddf.png)

![image](https://user-images.githubusercontent.com/42288570/197316684-33b73f24-b7c6-4616-ae16-ae83b139d55d.png)

```bash
ValueError: Can't fetch metadata for 'base64' from PyPI. Please make sure you have entered a correct package name.
```

**Comment by philippjfr** [comment] 2022-10-24 07:59
Thanks for reporting. At least on Linux it seems to correctly detect it as a standard library. Could you run this and see what it returns?

```python
from panel.io.mime_render import find_imports
find_imports("""
import base64
""")
```

Also maybe inspect to see if there's other omissions there:

```python
from panel.io.mime_render import _STDLIBS
print(_STDLIBS)
```

**Comment by MarcSkovMadsen** [comment] 2022-10-24 15:03
When running

```python
import panel as pn
from panel.io.mime_render import find_imports
find_imports("""
import base64
""")
```

I see no output. The second script outputs

```bash
['_abc', '_ast', '_codecs', '_collections', '_functools', '_imp', '_io', '_locale', '_operator', '_peg_parser', '_signal', '_sre', '_stat', '_string', '_symtable', '_thread', '_tracemalloc', '_warnings', '_weakref', 'atexit', 'builtins', 'errno', 'faulthandler', 'gc', 'itertools', 'marshal', 'posix', 'pwd', 'sys', 'time', 'xxsubtype', '__future__', '_aix_support', '_bootlocale', '_bootsubprocess', '_collections_abc', '_compat_pickle', '_compression', '_markupbase', '_osx_support', '_py_abc', '_pydecimal', '_pyio', '_sitebuiltins', '_strptime', '_sysconfigdata__linux_x86_64-linux-gnu', '_sysconfigdata_x86_64_conda_cos6_linux_gnu', '_sysconfigdata_x86_64_conda_linux_gnu', '_threading_local', '_weakrefset', 'abc', 'aifc', 'antigravity', 'argparse', 'ast', 'asynchat', 'asyncio', 'asyncore', 'base64', 'bdb', 'binhex', 'bisect', 'bz2', 'cProfile', 'calendar', 'cgi', 'cgitb', 'chunk', 'cmd', 'code', 'codecs', 'codeop', 'collections', 'colorsys', 'compileall', 'concurrent', 'configparser', 'contextlib', 'contextvars', 'copy', 'copyreg', 'crypt', 'csv', 'ctypes', 'curses', 'dataclasses', 'datetime', 'dbm', 'decimal', 'difflib', 'dis', 'distutils', 'doctest', 'email', 'encodings', 'ensurepip', 'enum', 'filecmp', 'fileinput', 'fnmatch', 'formatter', 'fractions', 'ftplib', 'functools', 'genericpath', 'getopt', 'getpass', 'gettext', 'glob', 'graphlib', 'gzip', 'hashlib', 'heapq', 'hmac', 'html', 'http', 'idlelib', 'imaplib', 'imghdr', 'imp', 'importlib', 'inspect', 'io', 'ipaddress', 'json', 'keyword', 'lib2to3', 'linecache', 'locale', 'logging', 'lzma', 'mailbox', 'mailcap', 'mimetypes', 'modulefinder', 'multiprocessing', 'netrc', 'nntplib', 'ntpath', 'nturl2path', 'numbers', 'opcode', 'operator', 'optparse', 'os', 'pathlib', 'pdb', 'pickle', 'pickletools', 'pipes', 'pkgutil', 'platform', 'plistlib', 'poplib', 'posixpath', 'pprint', 'profile', 'pstats', 'pty', 'py_compile', 'pyclbr', 'pydoc', 'pydoc_data', 'queue', 'quopri', 'random', 're', 'reprlib', 'rlcompleter', 'runpy', 'sched', 'secrets', 'selectors', 'shelve', 'shlex', 'shutil', 'signal', 'site', 'smtpd', 'smtplib', 'sndhdr', 'socket', 'socketserver', 'sqlite3', 'sre_compile', 'sre_constants', 'sre_parse', 'ssl', 'stat', 'statistics', 'string', 'stringprep', 'struct', 'subprocess', 'sunau', 'symbol', 'symtable', 'sysconfig', 'tabnanny', 'tarfile', 'telnetlib', 'tempfile', 'test', 'textwrap', 'this', 'threading', 'timeit', 'tkinter', 'token', 'tokenize', 'trace', 'traceback', 'tracemalloc', 'tty', 'turtle', 'turtledemo', 'types', 'typing', 'unittest', 'urllib', 'uu', 'uuid', 'venv', 'warnings', 'wave', 'weakref', 'webbrowser', 'wsgiref', 'xdrlib', 'xml', 'xmlrpc', 'zipapp', 'zipfile', 'zipimport', 'zoneinfo', '_asyncio', '_bisect', '_blake2', '_bz2', '_codecs_cn', '_codecs_hk', '_codecs_iso2022', '_codecs_jp', '_codecs_kr', '_codecs_tw', '_contextvars', '_crypt', '_csv', '_ctypes', '_ctypes_test', '_curses', '_curses_panel', '_datetime', '_decimal', '_elementtree', '_hashlib', '_heapq', '_json', '_lsprof', '_lzma', '_md5', '_multibytecodec', '_multiprocessing', '_opcode', '_pickle', '_posixshmem', '_posixsubprocess', '_queue', '_random', '_sha1', '_sha256', '_sha3', '_sha512', '_socket', '_sqlite3', '_ssl', '_statistics', '_struct', '_testbuffer', '_testcapi', '_testimportmultiple', '_testinternalcapi', '_testmultiphase', '_tkinter', '_uuid', '_xxsubinterpreters', '_xxtestfuzz', '_zoneinfo', 'array', 'audioop', 'binascii', 'cmath', 'fcntl', 'grp', 'math', 'mmap', 'nis', 'ossaudiodev', 'parser', 'pyexpat', 'readline', 'resource', 'select', 'spwd', 'syslog', 'termios', 'unicodedata', 'xxlimited', 'zlib']
```

**Comment by philippjfr** [comment] 2022-10-24 15:42
So I definitely can't reproduce the problem on Linux and tried to add some tests here:

https://github.com/holoviz/panel/pull/4050

**Comment by philippjfr** [comment] 2022-11-17 17:02
Unless we can find an actual reproducer I'm closing this.

**Closed by philippjfr** 2022-11-17 17:02 UTC
Labels: type: bug, webassembly
