### ISSUE TITLE
Vertical RangeSliders and Vertical Sliders not Displaying Properly

### ISSUE THREAD

**Issue by HenningBeyer** [holoviz/panel#6728] opened 2024-04-15 06:40 UTC
Related to my previous feature request #6725, there is an issue/bug with the displaying of the vertical RangeSlider: It's height is completely squished, when using `orientation='vertical'` so that the two sliders are not dragable and the component unusable. Often the RangeSlider also displays values of 'NaN' after being dragged only slightly. 

The same issue is also observable for the regular Sliders, for which only the drag-button renders without a visible bar.

I have tried adjusting `min_height, max_heigth, height_policy, and sizing_mode` but this did not fix it for me.

I use Python 3.9.5, panel 1.4.0, pyviz_comms 3.0.2 and jupyterlab 4.1.5. Both the Jupyter Lab displaying and the served app displaying did not work properly.

---

You can try `pn.widgets.RangeSlider(start=0, end=len=100, step=1, bar_color='#50A0F0', orientation='vertical')`, or `pn.widgets.FloatSlider(start=10, end=100, step=1, orientation='vertical')` to see it.

---

But you can also try my use case below. The vertical RangeSlider would be useful to me for to slice a DataFrame along the vertically displayed index. I want to only take the sliced DataFrame's values into account for some calculations like a DataFrame summary with time series data.

import panel as pn
import pandas as pd
import numpy as np
pn.extension()

df = pd.DataFrame(np.random.rand(100,100))
a = pn.pane.DataFrame(df, max_height=300, max_rows=9, sizing_mode="stretch_both", max_width=800) 
b = pn.pane.DataFrame(df.describe(percentiles=[0.05,0.25,0.5,0.75,0.95])[1:], 
                      max_height=300, max_rows=9, sizing_mode="stretch_both", max_width=800)
c = pn.widgets.RangeSlider(start=0, end=len(df), step=1, bar_color='#50A0F0',
                           orientation='vertical', min_height=100, height_policy='max') 
d = pn.Row(pn.layout.Tabs(('Data Preview',a),('Data Summary',b)),c)
d.servable()

**Comment by philippjfr** [comment] 2024-05-14 13:53
Thanks for the report, going to close this one as a duplicate of https://github.com/holoviz/panel/issues/4993

**Closed by philippjfr** 2024-05-14 13:53 UTC
Labels: bokeh
