### ISSUE TITLE
Tabulator very slow with large number of columns

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2327] opened 2021-05-18 14:13 UTC
When you run the code below and 1) Navigate to the "Dataset" page 2) click "Load" you 

- experience a very, very slow application

```python
import panel as pn
import pandas as pd
import numpy as np


pn.extension(sizing_mode = 'stretch_width')

df = pd.DataFrame()

ID_CreditSC_App = pn.template.BootstrapTemplate()

mainColumn = pn.Column()

df_tabulator = pn.widgets.Tabulator(df,name='Original Dataset', disabled =True, height=400, pagination='local', page_size=50)
df_tabulator1 = pn.widgets.Tabulator(df,name='Original Dataset', disabled =True, height=400, pagination='local', page_size=50)

tabs_dataset = pn.Tabs(
    (df_tabulator),
    (df_tabulator1)
)

multiSelect = pn.widgets.MultiSelect(name='Segmentation value', size=8)

btn_main    = pn.widgets.Button(name='Main')
btn_dataset = pn.widgets.Button(name='Dataset')
btn_loadSelector = pn.widgets.Button(name='Load')
btn_loadTable = pn.widgets.Button(name='Load')

def mainClick(event):
    mainColumn[:] = mainView

def datasetClick(event):
    mainColumn[:] = datasetView

def init_df():
    for i in range(100):
        df.insert(0, 'Column' + str(i), np.random.randint(0, 10, 10000))

def loadSelector(event):
    multiSelect.options = df['Column1'].values.tolist()

def loadTable(event):
    df_tabulator.value = df
    df_tabulator1.value = df



btn_main.on_click(mainClick)
btn_dataset.on_click(datasetClick)
btn_loadSelector.on_click(loadSelector)
btn_loadTable.on_click(loadTable)


mainView = [btn_loadSelector,multiSelect]
datasetView = [btn_loadTable, tabs_dataset]

init_df()

ID_CreditSC_App.sidebar.append(btn_main)
ID_CreditSC_App.sidebar.append(btn_dataset)
ID_CreditSC_App.main.append(mainColumn)
ID_CreditSC_App.servable()
```

Panel: 0.12.0a11

**Comment by MarcSkovMadsen** [comment] 2021-05-18 14:21
I will take a first look at minimize the example.

**Comment by MarcSkovMadsen** [comment] 2021-05-18 14:39
This works a bit better

```python
import panel as pn
import pandas as pd
import numpy as np


pn.extension(sizing_mode = 'stretch_width')

df = pd.DataFrame()

ID_CreditSC_App = pn.template.BootstrapTemplate()

mainColumn = pn.Column()

df_tabulator = pn.widgets.Tabulator(name='Original Dataset', disabled =True, height=400, pagination='local', page_size=50)
df_tabulator1 = pn.widgets.Tabulator(name='Original Dataset', disabled =True, height=400, pagination='local', page_size=50)

tabs_dataset = pn.Tabs(
    (df_tabulator),
    (df_tabulator1)
)

multiSelect = pn.widgets.MultiSelect(name='Segmentation value', size=8)

btn_main    = pn.widgets.Button(name='Main')
btn_dataset = pn.widgets.Button(name='Dataset')
btn_loadSelector = pn.widgets.Button(name='Load')
btn_loadTable = pn.widgets.Button(name='Load')

def start_loading():
    mainColumn.loading=True

def stop_loading():
    mainColumn.loading=False


def mainClick(event):
    start_loading()
    mainColumn[:] = mainView
    stop_loading()

def datasetClick(event):
    start_loading()
    mainColumn[:] = datasetView
    stop_loading()

def init_df():
    start_loading()
    columns = ["Column" + str(i) for i in range(0,100)]
    df= pd.DataFrame(np.random.randint(0,100,size=(100, 100)), columns=columns)
    stop_loading()
    return df

def loadSelector(event):
    start_loading()
    print(df.columns)
    multiSelect.options = df['Column1'].values.tolist()
    stop_loading()

def loadTable(event):
    start_loading()
    df_tabulator.value = df
    df_tabulator1.value = df
    stop_loading()

btn_main.on_click(mainClick)
btn_dataset.on_click(datasetClick)
btn_loadSelector.on_click(loadSelector)
btn_loadTable.on_click(loadTable)


mainView = [btn_loadSelector,multiSelect]
datasetView = [btn_loadTable, tabs_dataset]

def init_data():
    start_loading()
    df=init_df()
    df_tabulator.value = df
    df_tabulator1.value = df
    stop_loading()

start_loading()
pn.state.onload(init_data)


ID_CreditSC_App.sidebar.append(btn_main)
ID_CreditSC_App.sidebar.append(btn_dataset)
ID_CreditSC_App.main.append(mainColumn)
ID_CreditSC_App.servable()
```

**Comment by MarcSkovMadsen** [comment] 2021-05-18 14:40
Torben. You need to provide a smaller example. Remove everything that is not needed. Like the template etc.

**Comment by philippjfr** [comment] 2021-05-18 14:52
Please test against latest dev releases, i.e. 0.12.0a11, which you can install with `pip install panel==0.12.0a11 --pre` or `conda install -c pyviz/label/dev panel=0.12.0a11`. I fixed a few issues with Tabulator recently.

**Comment by philippjfr** [comment] 2021-05-18 15:28
Okay just tried and definitely something interesting happening here. Profiler flame graph looks very ominous:

<img width="803" alt="Screen Shot 2021-05-18 at 5 27 28 PM" src="https://user-images.githubusercontent.com/1550771/118679682-5d4f8200-b7fe-11eb-853a-d50a607d4eda.png">

Will need investigating, there's definitely one redraw too many happening there but even so Tabulator seems to be struggling a good bit here.

**Comment by philippjfr** [comment] 2021-05-18 15:52
This appears to be a known issue: https://github.com/olifolkerd/tabulator/issues/1090

Tabulator does not seem to scale well with large numbers of columns but I hope there's some optimizations we can still make here.

**Comment by philippjfr** [comment] 2021-05-18 16:02
Also I hope you don't mind @MarcSkovMadsen but I've edited your posts. The errors you were seeing have already been fixed.

**Comment by douglas-raillard-arm** [comment] 2021-07-02 18:31
Not sure if I'm hitting the same issue but Tabular is significantly slower than DataFrame widget for my case (10 columns, 1500 rows). Even with page_size=100 I get some noticeable lag.
DataFrame is able to display the whole table at once without breaking a sweat.

**Comment by MarcSkovMadsen** [comment] 2021-07-02 19:16
Could you provide a minimum reproducible example @douglas-raillard-arm . There can be a ton of potential cause whether you are in notebook, on server, using template,…..

**Comment by MarcSkovMadsen** [comment] 2021-07-02 19:17
@philippjfr . Do we know that this is not because of the panel implementation triggering a ton of rerendering/ updates?

**Comment by douglas-raillard-arm** [comment] 2021-07-05 10:38
@MarcSkovMadsen I'm using:
* panel 0.12.0rc3
* jupyterlab 3.0.16
* Chromium 91.0.4472.114 Arch Linux
* Firefox Mozilla Firefox 89.0.2

```
import panel as pn
import pandas as pd

pn.extension('tabulator')

size = int(1e4)
df_lag = pd.DataFrame(
    {
        'a': [1] * size,
        #'b': ['hello world'] * size,
    },
)

cls = pn.widgets.Tabulator
#cls = pn.widgets.DataFrame
cls(
    df_lag,
    height=400,
)
```
When using Tabulator:
* the scrollbar does not really work: as soon as you move your mouse trying to drag the bar, the bar will move a bit and then just stay where it is, unless you go really slowly.
* Removing height=400 makes the tab unresponsive, chromium asks if the tab should get killed and I got one CPU that is used 100%. Firefox exhibits the same problem. There does not seem to be a memory issue though.

When using DataFrame widget, everything is smooth and works, even without a fixed height (although it does limit itself automatically and adds a scrollbar, which might not be the case with Tabulator, so the comparison might be unfair)

**Comment by philippjfr** [comment] 2021-07-05 11:28
Thanks for your investigation, seems like that at minimum we should add a `max_height` to Tabulator so you don't end up making your browser render a huge table all at once.

**Comment by philippjfr** [comment] 2021-11-09 18:42
I'm now comfortable closing this issue after upgrading to Tabulator 5.0. The performance seems to be much improved and it's unlikely we can do anything else on our end to improve it further.

> the scrollbar does not really work: as soon as you move your mouse trying to drag the bar, the bar will move a bit and then just stay where it is, unless you go really slowly.

Also seems to work much better since the upgrade to Tabulator 5.0 in #2898.

> Removing height=400 makes the tab unresponsive, chromium asks if the tab should get killed and I got one CPU that is used 100%. Firefox exhibits the same problem. There does not seem to be a memory issue though.

This will be covered by either limiting the maximum height or by enabling pagination by default if the number of rows exceeds a certain number https://github.com/holoviz/panel/issues/2841

**Closed by philippjfr** 2021-11-09 18:42 UTC
Labels: type: enhancement

**Comment by douglas-raillard-arm** [comment] 2022-04-04 13:37
I can confirm that recent releases of Panel have fixed the issue for my use case (lots of rows)

**Comment by lransona** [comment] 2023-05-09 08:40
Hi All,
Regarding the problem that you are mentioning with the columns for pn.Tabulator, I am having the same issue (version:Panel 0.14.3 py310haa95532_0). I have try different Dataframes shapes but clearly for shapes with more than 100 columns, the component doesn’t work properly. Here some examples I have tested:
`
Shape= (81, 63)
Shape= (53, 12)
Shape= (206, 256)
Shape= (590, 21)
Shape= (53, 12)
Shape= (206, 256)
Shape= (240, 48)
`
It is also worth mentioning, that when loading sheets with 256 columns, something breaks and the application becomes unstable, the response time is really slow and sometimes I even get the image.
![image](https://user-images.githubusercontent.com/28267326/237042030-7d3783b6-cbb1-487e-8229-adb3b7736d78.png)

I have tried to switch to pn.DataFrame but the problem is even worse.

Is there a way around the number of columns problem for the Tabulator in panel ?
Thanks in advance for the assistance and any help you may provide.
