### ISSUE TITLE
Template app served using panel.Serve exists only in one instance

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1161] opened 2020-03-16 13:52 UTC
#### My Pain

I'm trying to `panel.serve` a list of apps where some are `panel.Template`s.

When having a Template based app running in multiple browser windows they update together. I.e. only one instance exists across users.

#### Additional Context

My guess is that it's related to https://github.com/holoviz/panel/issues/1160. But I'm not sure.

FYI. @philippjfr . I believe this is a major issue because you cannot currently `panel.Serve` multiple apps based on `panel.Template`.

#### Screenshot

![template_issue](https://user-images.githubusercontent.com/42288570/76764686-8b1dde80-6795-11ea-800e-2d3e24a8649e.gif)

#### Code

```python
import holoviews as hv
import panel as pn

TEMPLATE = """
<!-- This template is inspired by
- Bokeh Template. See https://panel.pyviz.org/user_guide/Templates.html
-->
{% extends base %}

<!-- goes in head -->
{% block postamble %}
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link
    href="https://orstedcdn.azureedge.net/-/media/WWW/Images/Corp/Graphics/Icons/favicon.ico?rev=ba82db4b63a04e21be8b5472e7fe45c9"
    rel="icon" type="image/x-icon" />
{% endblock %}

<!-- goes in body -->
{% block contents %}

{{ embed(roots.header) }}
{{ embed(roots.main) }}

{% endblock %}
"""

CSS = """
body{
    overflow-x: hidden;
    overflow-y: hidden;
    margin: 0px;
    background-color: rgb(48,48,48);
    color: rgb(236,236,236);
  }

.bk-root .bk {
  font-family: OrstedSansRegular, sans-serif, Verdana;
}
/* Grid */

#page {
display: grid;
width: 100%;
height: 100vh;
grid-template: [header-left] "head head" 60px [header-right]
                [main-left]   "main  main" 1fr  [main-right] / 1fr 1fr;
}

header {
grid-area: head;
color: rgb(236,236,236);
background-color: rgb(100,76,118);

box-shadow: 3px 3px 10px grey;

z-index: 1000;

text-align: center;
font-size: 1rem;
}


main {
color: rgb(236,236,236);
background-color: rgb(48,48,48);
grid-area: main;
overflow-x: hidden;
overflow-y: scroll;
}



/* Custom Scrollbar.
See https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp */
::-webkit-scrollbar {
    width: 10px;
  }

::-webkit-sc

/* Track */
::-webkit-scrollbar-track {
  box-shadow: inset 0 0 1px grey;
  border-radius: 1px;
}

/* Handle */
::-webkit-scrollbar-thumb {
  background: darkgrey;
  border-radius: 1px;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: lightgrey;
}

header a:link {
  color: white;
  text-decoration: none;
}
header a:visited {
  color: white;
}
header a:hover{
  color: white;
}
.bk.app-title a{
  color: rgb(236,236,236);
  background-color: inherit;
  text-align: center;
  font-size: 1rem;
}
.bk.app-title a:link {
  text-decoration: none;
}
.bk.app-title a:hover{
  color: white;
}
div.bk.navigation div.bk button {
  text-align: left !important;
}

option:checked {
  background: rgb(142, 205, 200) linear-gradient(0deg, rgb(142, 205, 200) 0%, rgb(142, 205, 200) 100%) !important;
}
"""


class DashboardTemplate(pn.Template):
    """A Basic App Template"""

    def __init__(self, **params):
        template = TEMPLATE

        self.header = pn.Row(background="black")
        self.main = pn.Column(background="salmon")

        items = {
            "header": self.header,
            "main": self.main,
        }
        super().__init__(template=template, items=items, **params)


def app_template():
    app = DashboardTemplate()
    app.header[:] = [pn.pane.Markdown("header")]
    app.main[:] = ["# My App", pn.widgets.Select(name="Select", options=["a", "b"])]
    return app


def app_no_template():
    return pn.widgets.Select(name="Select", options=["a", "b"])


APP_ROUTES = {
    "no-template": app_no_template,
    "template": app_template(),
}

pn.serve(APP_ROUTES, port=14033, dev=True)
```

**Comment by philippjfr** [comment] 2020-03-19 16:50
Closing as duplicate of #1160 since this behavior is expected given the above code but fixing #1160 will let you get the expected behavior.

**Closed by philippjfr** 2020-03-19 16:50 UTC
Labels: type: bug

**Comment by MarcSkovMadsen** [comment] 2020-03-19 18:33
Thanks.

**Comment by gmatteo** [comment] 2021-07-01 22:56
I'm using `panel.serve` to serve a list of apps constructed with panel.Template and
I'm encoutering the same problem descrived in this issue i.e. only one instance exists across users.
Only template-based apps are affected. 

I'm using python 3.8 and

```
Name: panel
Version: 0.11.3

Name: bokeh
Version: 2.3.2
```

**Comment by MarcSkovMadsen** [comment] 2021-07-02 02:07
Hi @gmatteo 

Could you open a new issue with a minimum reproducible example as this one has been closed? Thx.

**Comment by gmatteo** [comment] 2021-07-02 02:12
> Could you open a new issue 

Sure. 

> with a minimum reproducible example as this one has been closed? Thx

Please note that your example is already enough to reproduce the problem so I'm gonna copy your python example in the new issue. It's much easier than using my version that is available [here](https://github.com/abinit/abipy/blob/develop/abipy/scripts/abigui.py)
