### ISSUE TITLE
Model 'panel.models.markup.HTML' does not exist

### ISSUE THREAD

**Issue by sdc50** [holoviz/panel#1205] opened 2020-04-01 03:38 UTC
When embedding a Panel app in Django I can only get it to render using the following:
```
Bokeh=1.4.0
Panel=0.6.4
Holoviews=1.12.7
```
Using any other version of Panel (0.7.0-0.8.1) produces the following browser console error:

```
Error rendering Bokeh items: Error: Model 'panel.models.markup.HTML' does not exist. This could be due to a widget or a custom model not being registered before first usage.
```

I also get the same error with the most recent versions:

```
Bokeh=2.0.0
Panel=0.9.3
Holoviews=1.13.1
```

**Comment by sdc50** [comment] 2020-04-01 03:43
@mattpap, @philippjfr I'm assuming that `bokeh.core.templates.AUTOLOAD_JS` is what is registering most widgets. Is there a way to manually register `panel.models.markup.HTML` so that I can get this to work while waiting for a fix?

**Comment by philippjfr** [comment] 2020-04-01 08:26
@mattpap with bokeh 2.0.1 I'm getting 

>GET http://localhost:8000/static/extensions/panel/panel.min.js net::ERR_ABORTED 404 (Not Found)

I'm guessing the Django server implementation wasn't updated?

**Comment by philippjfr** [comment] 2020-04-01 09:19
So I haven't yet been able to add a route to Django to serve the extensions, so the only way forward for now is to add either:

```
from bokeh.settings import settings
settings.resources = 'cdn'
settings.resources = 'inline'
```

The CDN approach will work once I've pushed out Panel 0.9.4, while the inline approach should already work.

**Comment by mattpap** [comment] 2020-04-01 09:36
> I'm guessing the Django server implementation wasn't updated?

Correct.

**Comment by philippjfr** [comment] 2020-04-01 09:44
Hmm, the original report here wasn't from 2.0.1 where the changes to serving extensions were introduced. I would have expected 2.0.0 to work correctly.

**Comment by philippjfr** [comment] 2020-04-01 09:47
I'm now also wondering how the static handling works at all in a production Django server. Don't they recommend to turn off the static file serving (see https://docs.djangoproject.com/en/3.0/howto/static-files/):

>During development, if you use django.contrib.staticfiles, this will be done automatically by runserver when DEBUG is set to True (see django.contrib.staticfiles.views.serve()).

>This method is grossly inefficient and probably insecure, so it is unsuitable for production.

**Comment by mattpap** [comment] 2020-04-01 09:58
> `Error rendering Bokeh items: Error: Model 'panel.models.markup.HTML' does not exist.` (...)

This error indicates that at least bokeh.js was loaded. I will need to debug this to avoid guessing what's exactly wrong in this situation.

**Comment by sdc50** [comment] 2020-04-01 22:20
> I'm now also wondering how the static handling works at all in a production Django server.

There is a CLI command that collects all static files into a `STATIC_ROOT` directory that is specified in the settings. Typically you would then configure your production server (e.g. Apache, Nginx, etc.) to serve static files directly from that directory. Other requests are then forwarded to the production asgi server (e.g. Daphne). 

However, (@msouff correct me if I'm wrong here), the Bokeh static files are not served the same way as the Django static files. When a web socket is first established with a Bokeh handler then `AUTOLOAD_JS.render` is called with values from the result of `bokeh.resources.Resources`. I'm assuming that's when the static files for Bokeh are loaded.

**Comment by sdc50** [comment] 2020-04-02 01:08
@mattpap I don't know if this would be helpful in debugging, but the example code that I used to test this is here: https://github.com/tethysplatform/tethysapp-bokeh_tutorial

It has both the Sea Surface Bokeh example and the Shapes Panel example embedded. The Sea Surface example works, but the Shapes example does not.

The caveat is that it is not a just a Django application; it's actually a [Tethys Platform](http://www.tethysplatform.org/) (a framework built on Django) application.

**Instructions for Setting up the App in Tethys:**
<details>

Broken version:
```bash
conda create -n tethys -c tethysplatform/label/dev -c conda-forge tethys-platform panel bokeh holoviews
conda activate tethys
tethys db configure
git clone https://github.com/tethysplatform/tethysapp-bokeh_tutorial.git
cd tethysapp-bokeh_tutorial
tethys install -d -w
tethys manage start
```
The last command will start a server running on http://127.0.0.1:8000/.
The default user credentials are:
Username: admin
Password: pass

Cleaning up:
In addition to the conda environment and the cloned repository Tethys configures a Postgresql database in ~/.tethys/psql that runs on port 5436 by default. To stop the DB server and delete the DB directory run:
```
tethys db purge
```
That will delete the `psql` dir so you may also want to run:

```
rm -rf ~/.tethys
```

Working version:
```bash
conda create -n tethys -c tethysplatform -c conda-forge tethys-platform panel=0.6.4 bokeh=1.4.0 holoviews=1.12.7
conda activate tethys
tethys db configure
git clone https://github.com/tethysplatform/tethysapp-bokeh_tutorial.git
cd tethysapp-bokeh_tutorial
git checkout -b solution solution-3.0
tethys install -d -w
tethys manage start
```
</details>

**Comment by philippjfr** [comment] 2020-04-02 01:10
This is also reproducible using the Django examples in this repo, I was running ./examples/apps/django_multi_apps.

**Comment by sdc50** [comment] 2020-04-02 12:06
> So I haven't yet been able to add a route to Django to serve the extensions, so the only way forward for now is to add either:
> 
> ```
> from bokeh.settings import settings
> settings.resources = 'cdn'
> settings.resources = 'inline'
> ```

@philippjfr Where do you add this to get the Django examples to work? I've tried in several spots with the Tethys examples, but it doesn't seem to have any affect.

**Comment by philippjfr** [comment] 2020-04-02 12:59
So I realized last night that there were some other regressions with bokeh 2.0.1 which means this only works for a develop install right now. I did release Panel 0.9.4 last night as well which should have fixed this, but I messed up publishing the npm package so the CDN option won't work until the 0.9.5 release, which should be soon. You should however be able to install 0.9.4 and get the inline option to work by putting `settings.resources = 'inline'` into the Django settings.py file.

**Comment by OwenMyers** [comment] 2020-04-02 15:23
Thank you so much! You just saved me a lot of time. I had been wrestling with this for a couple of days and now it just works.

**Comment by philippjfr** [comment] 2020-04-02 15:34
Sorry for wasting so much of your time, this revealed in a hole in our testing since I only tested against a dev install and not the packaged installs.

**Comment by OwenMyers** [comment] 2020-04-02 17:21
No problem at all. Fantastic to have it working. Thanks for the quick resolution to this issue!

**Comment by philippjfr** [comment] 2020-06-20 13:21
Will close, these issues have now been resolved in Bokeh.

**Closed by philippjfr** 2020-06-20 13:21 UTC
Labels: type: bug
