### ISSUE TITLE
panel component can't interact properly in bokeh server

### ISSUE THREAD

**Issue by ShukriChiu** [holoviz/panel#1235] opened 2020-04-06 13:52 UTC
I update Panel into 0.9.5 and bokeh to 2.0.1.

The following "simple" code doesn't work right.

![image](https://user-images.githubusercontent.com/5136543/78565649-cbcabe00-7850-11ea-815d-1ed4a858fa3e.png)

If I change the value in the sider, the bottom value should response to change too, however it remains the same initial value.

**Comment by maximlt** [comment] 2020-04-06 15:51
Hi @ShukriChiu,

Could you try this more straightforward sample code (as described in the [docs](https://panel.holoviz.org/getting_started/index.html)):
```python
import panel as pn
pn.extension

def f(x):
    return x

pn.interact(f, x=10)
```

**Comment by philippjfr** [comment] 2020-04-06 16:21
Thanks for the issue. Three things, you are asking about "bokeh server" but you seem to be working in a notebook is that correct? Secondly I would remove `output_notebook` it is not needed and (although unlikely) may interfere. Lastly could you tell us what notebook environment you are using? If you are in JupyterLab have you installed the JupyterLab extension with:

```
jupyter labextension install @pyviz/jupyterlab_pyviz
```

**Comment by ShukriChiu** [comment] 2020-04-06 18:46
![image](https://user-images.githubusercontent.com/5136543/78593705-a00ffe00-7879-11ea-82fd-6d0b44507215.png)
![image](https://user-images.githubusercontent.com/5136543/78593737-ab632980-7879-11ea-9971-b59567296ff5.png)

Because I have installed @bokeh/jupyter_bokeh extension, the result showed in notebook should be the same in a Bokeh server.

If I remove the output_notebook option, the output will be blank.

**Comment by philippjfr** [comment] 2020-04-07 00:28
Two things, panel absolutely does not depend on jupyter_bokeh or output_notebook, if nothing display without output_notebook something fundamental is broken. Secondly output in the notebook and bokeh server are very different things and use very different ways of loading the required JS dependencies and communicating even if they should behave the same (at least in Panel). I have a couple questions/suggestions:

1) Please post the output of the Javascript console in your browser **without** running output_notebook
2) Please post the version of the jupyterlab_pyviz extension and potentially upgrade to latest.
3) Please let us know where you installed Panel 0.9.5 from so I can reproduce exactly.

**Comment by philippjfr** [comment] 2020-04-07 01:50
I can reproduce this now with the conda-forge package.

**Comment by ShukriChiu** [comment] 2020-04-07 05:55
yes, I'm using conda-forge 0.9.5 version.

**Comment by ShukriChiu** [comment] 2020-04-07 08:54
![image](https://user-images.githubusercontent.com/5136543/78649572-367f0680-78f0-11ea-81fe-49155410e34f.png)

After switching to pip 0.9.5 panel, I can successfully render the panel object, but I still can't get the dynamic response.

**Comment by ShukriChiu** [comment] 2020-04-07 09:03
I have tested the link example. It doesn't work too.
https://panel.holoviz.org/user_guide/Links.html
![image](https://user-images.githubusercontent.com/5136543/78650416-785c7c80-78f1-11ea-9549-94b8792c8239.png)

after I pressed enter, the right markdown text doesn't change. If I use python to direct change its value, it actually changed after I re-render the object.

By the way, the example on 0.9.5 document page doesn't work either.
![image](https://user-images.githubusercontent.com/5136543/78650577-b0fc5600-78f1-11ea-992a-d374010158e6.png)

**Comment by mattpap** [comment] 2020-04-07 09:13
Closing as a duplicate of issue #1233. conda-forge package of panel 0.9.5 is broken currently. One can use `conda install -c pyviz panel` or `pip install panel` alternatively until the conda-forge package is fixed.

**Closed by mattpap** 2020-04-07 09:13 UTC

**Comment by philippjfr** [comment] 2020-04-07 10:37
@ShukriChiu The linking on that website will not work because there is no live kernel. We should probably add a note to those docs. As for your local copy I can only suggest sending us the output of your browsers JS console after you've started interacting.
