### ISSUE TITLE
Location value not decoded before application is loaded

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6144] opened 2024-01-02 12:30 UTC
I'm on the latest version of panel==1.3.6.

I was trying to sync the *active tab name* with `pn.state.location`. I noticed that this is hard because synced value is not deserialized before application load.

The below replicates the issue I see.

```python
import panel as pn
print("--- Reload ---")
widget = pn.widgets.Select(options=["Meta Data", "Other Value"])
pn.state.location.sync(widget, {"value": "tab"})

print("Before Load", widget.value)

@pn.depends(widget, watch=True)
def _handle_change(name):
    print("After Load: ", name)

widget.servable()
```

In the example in the video you see that a refresh prints.

```bash
--- Reload ---
Before Load Other%20Value
After Load:  Meta Data
2024-01-02 12:24:25,609 WebSocket connection closed: code=None, reason=None
2024-01-02 12:24:25,783 WebSocket connection opened
2024-01-02 12:24:25,783 ServerConnection created
After Load:  Other Value
```

In the video you can also see the widget value switch from "Meta Data" to "Other Value" instead of just being "Other Value" all the time.

I would expect that and need the *before* and *after* load values to be `Other Value`.

https://github.com/holoviz/panel/assets/42288570/3df69bf8-f15a-4eaa-9d5a-37a44b49a818

The consequence in my application is that first a very heavy tab is loaded and then it switches to the desired tab.

**Comment by philippjfr** [comment] 2024-01-09 23:15
Cannot reproduce this one.

**Comment by philippjfr** [comment] 2024-01-09 23:17
Does the VSCode proxy drop the URL parameters in the request maybe?

**Comment by philippjfr** [comment] 2024-01-10 17:03
@ahuang11 or @Hoxbro could you try to reproduce? If it's down to the JupyterHub proxy I'll close as we have no control.

**Comment by ahuang11** [comment] 2024-01-10 18:33
If I run this from CLI, it's synced properly. Not sure how to run it from VSCode (notebook)

<img width="634" alt="image" src="https://github.com/holoviz/panel/assets/15331990/101d2dce-b975-49b4-ab9e-89d3238de1e0">

**Comment by philippjfr** [comment] 2024-01-10 19:32
It's not intended to be run in a notebook.

**Comment by philippjfr** [comment] 2024-01-10 19:32
Anyway, thanks. I will close this as non-reproducible. As I said above the issue is likely in the proxy, not in Panel.

**Closed** 2024-01-10 19:33 UTC
Labels: more info needed
