### ISSUE TITLE
apply.opts change is applied to any displayed plots when used the first time

### ISSUE THREAD

**Issue by polinas123** [holoviz/panel#1603] opened 2020-09-30 10:03 UTC
this from the holoviz tutorial:
```
color_picker = pn.widgets.ColorPicker(name='Color', value='#00f300')
size_slider = pn.widgets.FloatSlider(name='Size', value=5, start=1, end=30)

color_histogram = dynamic_histogram.apply.opts(color=color_picker.param.value)
size_scatter = dynamic_scatter.apply.opts(size=size_slider.param.value)

pn.Column(
    pn.Row(color_picker, size_slider),
    pn.Row(color_histogram, size_scatter)
)
```
creates a color picker and a slider for size. The color is intended to be applied to the hist only, and the size is intended to be applied on the scatter only. However, on the first change of the size value - the hist size is changed too. subsequent changes will no longer change the hist size, only the scatter as expected. 

[here's a GIF to illustrate the point](https://www.dropbox.com/s/p7nf7qt4ddswwla/out.gif?dl=0)

**Comment by jbednar** [comment] 2020-09-30 12:47
Thanks for the report. I've transferred this issue to Panel because it's about slider handling, but it seems equally likely it's an issue in HoloViews.

**Comment by philippjfr** [comment] 2020-10-05 12:24
Please post a fully reproducible example, using a very basic example I was not able to reproduce this. Also please provide the versions of HoloViews and Panel you are using.

**Comment by philippjfr** [comment] 2020-10-05 12:25
This is also very unlikely to be Panel related (so I will probably transfer it back) but will wait for the reproducible example first.

**Comment by philippjfr** [comment] 2021-11-08 16:43
Never got a response here, closing.

**Closed by philippjfr** 2021-11-08 16:43 UTC
