### ISSUE TITLE
pn.Tabulator.selected_dataframe doesn't work with custom df.index

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/panel#2505] opened 2021-07-07 16:40 UTC
`IndexError: positional indexers are out-of-bounds`

**Comment by maximlt** [comment] 2022-01-25 08:45
It'd be nice if you could provide an example to reproduce this bug.

**Comment by maximlt** [comment] 2022-06-23 08:23
Closing as I cannot reproduce this issue, happy to re-open it again though if someone can provide an example to reproduce :)

**Closed by maximlt** 2022-06-23 08:23 UTC
Labels: component: tabulator
