### ISSUE TITLE
Standalone Panel app serving Plotly figure not working on Windows, but works in Jupyter Lab/Notebook

### ISSUE THREAD

**Issue by pybokeh** [holoviz/panel#1260] opened 2020-04-11 22:46 UTC
Hello!
For some reason, my [app](https://raw.githubusercontent.com/pybokeh/jupyter_notebooks/master/panel/pyscripts/county_choropleth_plotly.py) works on my Ubuntu machine, but does not work on my work Windows 10 laptop when I am trying to deploy it as a standalone Panel app.  However, it will work on my Windows 10 laptop in a Jupyter Lab/notebook environment.

In other words, on my Ubuntu machine, it works both in standalone mode or in jupyter notebook.
But on my Windows 10 machine, it does not work in standalone mode, but works in jupyter notebook.

When I visit the URL (http://localhost:8889), the browser tab title displays "Panel Application" and the page is just a blank white screen.

This is the output of my console that I launch panel .py file from using my Windows 10 machine:
```
(panel_dev) D:\panel\projects> python county_choropleth_plotly.py
Launching server at http://localhost:8889
WARNING:tornado.access:404 GET /static/extensions/panel/panel.min.js (::1) 0.88ms
WARNING:tornado.access:404 GET /static/extensions/panel/panel.min.js (::1) 1.18ms
WARNING:tornado.access:404 GET /static/extensions/panel/panel.min.js (127.0.0.1) 15.76ms
WARNING:tornado.access:404 GET /static/extensions/panel/panel.min.js (127.0.0.1) 1.59ms
```

Not sure if this is the difference, but on my Ubuntu machine's console, I don't get those tornado 404 warning messages.

When I serve Panel apps with my Windows 10 machine that don't include Plotly figures, they work fine, but my console output does still include tornado 404 warnings.

```
Launching server at http://localhost:8889
WARNING:param.CurvePlot01621: title_format is deprecated. Please use title instead
WARNING:param.CurvePlot01621:title_format is deprecated. Please use title instead
WARNING:param.CurvePlot01621: title_format is deprecated. Please use title instead
WARNING:param.CurvePlot01621:title_format is deprecated. Please use title instead
WARNING:tornado.access:404 GET /static/extensions/panel/panel.min.js (::1) 1.00ms
WARNING:tornado.access:404 GET /static/extensions/panel/panel.min.js (::1) 0.00ms
```

On my work Windows machine I am using Miniconda3 with Python version 3.8.2, so I have been installing panel (0.9.5) and plotly with conda command.  With panel, I've installed using the pyviz channel as I know there are on-going issues with the conda-forge version.  I also have the latest version of bokeh (2.0.1) and holoviews (1.13.2).

I also went to the extreme length of creating a Python 3.8 environment using the official Python installer at python.org and installed everything using only pip, but I am still getting the same problem.

I've tried setting and not setting the websocket origin, but still get the same problem.

**Comment by philippjfr** [comment] 2020-04-11 23:44
Thanks for the issue, this is a duplicate of https://twitter.com/TylerMorganMe/status/1247706877145776129?s=20 and will be resolved when bokeh 2.0.2 is released next week or by setting using CDN resources for bokeh server.

**Closed** 2020-04-11 23:44 UTC

**Comment by pybokeh** [comment] 2020-04-11 23:56
@philippjfr Thanks!  I am not a javascript dev, so I don't know how to debug issues related to javascript and I didn't know that this other issue is related.

For others who do not wish to create/set an environment variable, you can include this is in your script:
```
from bokeh.settings import settings
settings.resources = 'cdn'
settings.resources = 'inline'
```

**Comment by philippjfr** [comment] 2020-04-12 00:03
Thanks that's helpful!
