### ISSUE TITLE
Reduce friction of using Altair in responsive mode.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1516] opened 2020-08-05 04:59 UTC
Panel: 0.9.7
Altair: 4.1.0.

#### My Pain

I would like it to be easy to use Panel to develop awesome analytics apps using the wide range of Python viz tools.

One example where friction could be lowered is getting responsive Altair plots to work out of the box.

Here is an example where I would expect responsive behavior.

![image](https://user-images.githubusercontent.com/42288570/89373365-c723f280-d6e8-11ea-9494-1d9ba2781373.png)

```python
import altair as alt
import pandas as pd
import panel as pn
pn.extension("vega")

def get_altair_bar_data():
    return pd.DataFrame({
        'project': ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
        'score': [25, 57, 23, 19, 8, 47, 8],
        'goal': [25, 47, 30, 27, 38, 19, 4]
    })

def altair_bar_plot(data):
    bar_chart = alt.Chart(data).mark_bar().encode(
        x='project',
        y='score'
    ).properties(
        width="container" # alt.Step(40) #  #   # controls width of bar.
    )

    tick_chart = alt.Chart(data).mark_tick(
        color='red',
        thickness=2,
        size=40 * 0.9,  # controls width of tick.
    ).encode(
        x='project',
        y='goal'
    ).properties(
        width="container"
    )

    return bar_chart + tick_chart

data = get_altair_bar_data()
component = altair_bar_plot(data)
component_panel = pn.pane.Vega(component, sizing_mode="stretch_both")
pn.Column(
    component_panel,
    background="lightgray",
    width=500,
    sizing_mode="stretch_height",
    css_classes=["designer-centered-component"],
).servable()
```

#### Workaround

You can fix it by adding `.properties(width="container")` to the combined plot

![image](https://user-images.githubusercontent.com/42288570/89373529-3863a580-d6e9-11ea-883a-192750bdb7bd.png)

```python
import altair as alt
import pandas as pd
import panel as pn
pn.extension("vega")

def get_altair_bar_data():
    return pd.DataFrame({
        'project': ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
        'score': [25, 57, 23, 19, 8, 47, 8],
        'goal': [25, 47, 30, 27, 38, 19, 4]
    })

def altair_bar_plot(data):
    bar_chart = alt.Chart(data).mark_bar().encode(
        x='project',
        y='score'
    )

    tick_chart = alt.Chart(data).mark_tick(
        color='red',
        thickness=2,
        size=40 * 0.9,  # controls width of tick.
    ).encode(
        x='project',
        y='goal'
    )
    return (bar_chart + tick_chart).properties(
        width="container"
    )

data = get_altair_bar_data()
component = altair_bar_plot(data)
component_panel = pn.pane.Vega(component, sizing_mode="stretch_both")
pn.Column(
    component_panel,
    background="lightgray",
    width=500,
    sizing_mode="stretch_height",
    css_classes=["designer-centered-component"],
).servable()
```

#### Additional Context

You can discuss if this is a bug in Panel, a bug in Altair, if the Documentation of Panel should point this out more clearly or if this is just the way it is.

As you can see the altair plot is not fully centered. It would also be nice of it was.

**Comment by philippjfr** [comment] 2020-08-07 10:22
I'm struggling to see why this is a Panel level issue (or even an issue at all). Specifying `width="container"` in altair is both a plot level and a layout level concept and they have different results and use cases. So this behavior is exactly what I would expect. I'm of course always happy having a PR explaining these intricacies in the docs, but both altair and Panel are behaving reasonably here as far as I can tell.

**Comment by Midnighter** [comment] 2022-12-16 13:06
@MarcSkovMadsen have you found a way to make Altair be responsive in both directions? When I set `width="container"`, Altair simply falls back to the default height. `nvplot` is so nice because you can make it fully responsive while setting an aspect ratio that takes care of the dimensions. I haven't been able to reproduce that behavior with Altair.

**Comment by philippjfr** [comment] 2022-12-16 13:42
Definitely taking another look at this soon as we're in the process to upgrading to Bokeh 3.0 which completely overhauled the layout and sizing system and should give us much more control here.

**Comment by philippjfr** [comment] 2023-02-17 18:36
Note that the specification in the original example is ambiguous. In Panel 1.0 it will render and stretch but you have told the pane to stretch to full height but vega itself has not been told that it should match the container height, so you will end up with a stretched out plot. This means you will end up with this atrocity:

<img width="1050" alt="Screen Shot 2023-02-17 at 19 34 19" src="https://user-images.githubusercontent.com/1550771/219753754-0a3ecfa6-4e85-4b20-9fda-3761d535fc7a.png">

There may be some way to resolve this automatically but since my current solution resolves **all** existing Vega sizing issues I'm going to consider this resolved too because it can easily be fixed by setting `height="container"` on the plot.

<img width="1024" alt="Screen Shot 2023-02-17 at 19 36 26" src="https://user-images.githubusercontent.com/1550771/219754907-375523a7-216b-4b96-887c-fc2339a5dd5c.png">

**Closed** 2023-02-20 13:31 UTC
Labels: type: docs
