### ISSUE TITLE
panel.show() fails to find port so returns 404

### ISSUE THREAD

**Issue by kaedonkers** [holoviz/panel#498] opened 2019-07-02 11:26 UTC
Hello! Panel is awesome and really promising. 

I have in the past made interactive plots with HoloViews/GeoViews in JupyterLab and deployed them with using a Bokeh server. I have been trying to do the same with Panel using `panel.show(websocket_origin='foo.com', port='8889')` but the deployed app loses the port number at some point resulting in an empty app with 404 errors.
(URL below should be 

```pangeo-dev.informaticslab.co.uk/user/kaedonkers/proxy/9997/static/js/bokeh.min.js?v=--``` 

but it misses out the port)

Any advice?

![image](https://user-images.githubusercontent.com/32906197/60508953-b58d4180-9cc3-11e9-9b75-80d6af78ce6f.png)

![image (1)](https://user-images.githubusercontent.com/32906197/60509127-1fa5e680-9cc4-11e9-9c66-514437c64317.png)

![image (2)](https://user-images.githubusercontent.com/32906197/60508952-b4f4ab00-9cc3-11e9-8ed5-209d0883a0db.png)

**Comment by philippjfr** [comment] 2019-07-02 13:52
Could you describe how you used to deploy things with HoloViews? I can't see an issue with the way the port is passed through so maybe it's something else.

**Comment by philippjfr** [comment] 2020-07-28 13:27
Closing due to nonactivity. Please reopen if you can still reproduce and you can provide a reproducible example.

**Closed by philippjfr** 2020-07-28 13:27 UTC
Labels: type: bug
