### ISSUE TITLE
Altair selection demo not working

### ISSUE THREAD

**Issue by sriramvenkateshan** [holoviz/panel#4477] opened 2023-02-28 12:23 UTC
#### Version info
Python : 3.9.6
Jupyter-lab : 3.4.6
OS : Windows 10
Browser : Mozilla Firefox 110.0

#### I see the following error:
```
File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\param\parameterized.py", line 1585, in __getattr__
    raise AttributeError("'%s.param' object has no attribute %r" %
AttributeError: 'Selection.param' object has no attribute 'brush'
```

#### Code
Exactly a copy+paste of the example in demo here : https://pyviz-dev.github.io/panel/reference/panes/Vega.html#selections

#### Stack traceback 
```
Traceback (most recent call last):
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\sriramv\AppData\Local\Temp\ipykernel_25136\1948755520.py", line 41, in <module>
    pn.Row(vega_pane, pn.bind(filtered_table, vega_pane.selection.param.brush))
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\param\parameterized.py", line 1585, in __getattr__
    raise AttributeError("'%s.param' object has no attribute %r" %
AttributeError: 'Selection.param' object has no attribute 'brush'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py", line 1997, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\IPython\core\ultratb.py", line 1112, in structured_traceback
    return FormattedTB.structured_traceback(
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\IPython\core\ultratb.py", line 1006, in structured_traceback
    return VerboseTB.structured_traceback(
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\IPython\core\ultratb.py", line 859, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\IPython\core\ultratb.py", line 812, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\IPython\core\ultratb.py", line 730, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\stack_data\core.py", line 734, in lines
    pieces = self.included_pieces
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\stack_data\core.py", line 677, in included_pieces
    scope_pieces = self.scope_pieces
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\stack_data\core.py", line 617, in scope_pieces
    for piece in self.source.pieces
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\stack_data\core.py", line 106, in pieces
    return list(self._clean_pieces())
  File "c:\users\sriramv\appdata\local\programs\python\python39\lib\site-packages\stack_data\core.py", line 130, in _clean_pieces
    raise AssertionError("Pieces mismatches: %s" % mismatches)
AssertionError: Pieces mismatches: [{680, 681}, {696, 695}, {708, 709}, {714, 715}]
```

#### Screenshot
![image](https://user-images.githubusercontent.com/17196617/221853288-c24b50fb-fbb9-4ac6-8116-fd635cab1ba9.png)

**Comment by philippjfr** [comment] 2023-03-02 10:48
Closing as duplicate of #4486 which provides more detail.

**Closed by philippjfr** 2023-03-02 10:48 UTC
