### ISSUE TITLE
Multiple issues with Slider and Range Selector widgets when orientation is set to vertical

### ISSUE THREAD

**Issue by owenlamont** [holoviz/panel#5203] opened 2023-07-04 05:44 UTC
#### ALL software version info
OS: Windows 11 Pro 10.0.22621
Browser: Vivaldi 6.1.3035.111 (Stable channel) (64-bit)
Panel 1.1.1
Bokeh 3.1.1
Jupyterlab 4.0.2

#### Description of expected behavior and the observed behavior

The Editable sliders and range selector widgets appear to ignore the orientation argument completely and continue rendering horizontally whilst the slider widgets do render vertically but with an unusably short height (even when the height is manually specified). 

#### Complete, minimal, self-contained example code that reproduces the issue

Jupyter lab example - I tested in PyScript with the same results though.

```python
import panel as pn

pn.extension()
```

```python
pn.widgets.EditableRangeSlider(
    name='Range Slider',
    start=0,
    end=2.0,
    value=(0.5, 1.5),
    step=0.01,
    orientation="vertical"
)
```

```python
pn.widgets.EditableFloatSlider(start=0.0, end=2.0, orientation="vertical", height=200)
```

```python
pn.widgets.FloatSlider(start=0.0, end=2.0, orientation="vertical", height=200)
```

#### Screenshots or screencasts of the bug in action

![image](https://github.com/holoviz/panel/assets/12672027/9bd050ae-01b9-40a8-b0f5-2ed2d53ce058)

**Comment by Hoxbro** [comment] 2023-07-04 07:09
Thank you for the report! This is a duplicate of https://github.com/holoviz/panel/issues/4993.

**Closed by Hoxbro** 2023-07-04 07:09 UTC
