### ISSUE TITLE
Ability to add new items to MultiChoice

### ISSUE THREAD

**Issue by jlstevens** [holoviz/panel#5468] opened 2023-09-01 12:42 UTC
The [`MultiChoice` widget](https://panel.holoviz.org/reference/widgets/MultiChoice.html
) is a great way to work with tag systems but it does not have a way right now to add a new tag. e.g. if I type 'Kiwi' in the example:

<img width="373" alt="image" src="https://github.com/holoviz/panel/assets/890576/9ae989da-049a-466f-af4a-3a7feea91678">

There are no matches but it would be great if there was a `+` button (or similar) to specify Kiwi as an override. Ideally that could be in the text area that appears only when it says 'No results found'.

As an aside, I also note that in the docs, the `name` should be 'MultiChoice' and not 'MultiSelect':

```python
multi_choice = pn.widgets.MultiChoice(name='MultiSelect', value=['Apple', 'Pear'],
    options=['Apple', 'Banana', 'Pear', 'Strawberry'])
```

**Comment by philippjfr** [comment] 2023-10-13 07:58
Looks like this is a duplicate of: https://github.com/holoviz/panel/issues/5468

**Comment by philippjfr** [comment] 2023-10-13 07:59
Sorry, duplicate of https://github.com/holoviz/panel/issues/5047

**Closed by philippjfr** 2023-10-13 07:58 UTC
Labels: type: enhancement
