### ISSUE TITLE
Support LaTeX embedded in Markdown

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#842] opened 2019-12-04 13:02 UTC
#### My Pain

It's actually not so much a pain for me :-) But I know it is for a lot of other people in data science. They would like to be able to write LaTeX in markdown in their apps. This is not currently supported in Panel.

#### Solution

I would like support for LaTeX in Markdown. For example via markdown-katex at https://pypi.org/project/markdown-katex/

#### Example

```python
import panel as pn

text = r"""
``math
f(x) = \int_{-\infty}^\infty
\hat f(\xi)\,e^{2 \pi i \xi x}
\,d\xi
``
"""

app = pn.Column(pn.pane.Markdown(text))
app.servable()
```

(Change code to 3x`)

Currently renders in Panel as shown below

![image](https://user-images.githubusercontent.com/42288570/70144599-8f1e6880-169e-11ea-9ac3-5fa97775166d.png)

But should look something like

![image](https://user-images.githubusercontent.com/42288570/70144626-9e051b00-169e-11ea-8ec7-1acc22858a28.png)

**Comment by jbednar** [comment] 2019-12-04 15:01
Duplicate of https://github.com/holoviz/panel/issues/374

**Comment by philippjfr** [comment] 2019-12-04 23:47
Closed as duplicate.

**Closed** 2019-12-04 23:46 UTC
Labels: TRIAGE
