### ISSUE TITLE
FastTemplates not working on Windows - Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain".

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4114] opened 2022-11-14 06:43 UTC
panel=0.14.1, tornado=6.2, bokeh=2.4.3, os=windows, browser=edge or firefox

```python
import panel as pn

pn.extension(sizing_mode="stretch_width")

def page_outline():
    return """
Hello
"""

PAGES = [page_outline]

selector = pn.widgets.RadioButtonGroup(name="Page", value=PAGES[0], options=PAGES)

@pn.depends(selector)
def get_page(func):
    return func()

pn.template.FastListTemplate(
    site="Awesome Panel",
    title="Starter App",
    favicon="https://raw.githubusercontent.com/MarcSkovMadsen/awesome-panel-assets/320297ccb92773da099f6b97d267cc0433b67c23/favicon/ap-1f77b4.ico",
    sidebar=[selector], main=[get_page],
).servable()
```

![image](https://user-images.githubusercontent.com/42288570/201592590-f034c186-624a-4d19-9aa7-40a63d4d9f65.png)

```bash
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
fast-components.js:1 
        
       Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by MarcSkovMadsen** [comment] 2022-11-14 06:47
If I downgrade to panel==0.13.1, it looks like

![image](https://user-images.githubusercontent.com/42288570/201593291-c1ebbbbf-eeb2-40c2-a182-d84cbf410164.png)

**Comment by philippjfr** [comment] 2022-11-14 08:24
Isn't this a duplicate of https://github.com/holoviz/panel/issues/4080?

**Closed** 2022-11-14 08:25 UTC
Labels: type: bug
