### ISSUE TITLE
The same components show different input

### ISSUE THREAD

**Issue by wxn68** [holoviz/panel#5080] opened 2023-06-09 03:49 UTC
I Put the same WidgetBox on two tabs. If I change the input at the first tab, it will also change at the second tab. However, if I change the input at the second tab, the input at first tab is still unchanged. But the plot is already affected by the new input, it brings some confusion. 

main = pn.Tabs(("PnL", pn.Row(params,pnlPlot)), ("Scope", pn.Row(params,scopePlot)), ("Security", securityTab))

![企业微信截图_1686280839954](https://github.com/holoviz/panel/assets/71757916/310161d2-2ebc-416c-877a-122c77c9cffb)
![企业微信截图_16862808315928](https://github.com/holoviz/panel/assets/71757916/f83bb9ab-f6de-4ed6-babb-cacddde3e4ce)

**Comment by ahuang11** [comment] 2023-06-09 03:53
Maybe need to call a `.clone()` somewhere in there.

```
main = pn.Tabs(("PnL", pn.Row(params,pnlPlot)), ("Scope", pn.Row(params.clone(),scopePlot)), ("Security", securityTab))
```

**Comment by Hoxbro** [comment] 2023-06-09 07:56
Can you share a [minimal, reproducible example (MRE)](https://stackoverflow.com/help/minimal-reproducible-example)?

In general, a complete script only with the essential code, which can be copied/pasted and immediately run as-is with no modifications. This is much more useful than snippets.

**Comment by wxn68** [comment] 2023-06-09 08:28
Example: 
###########################
import panel as pn
from datetime import datetime

startDatePicker = pn.widgets.DatePicker(name="Start Date", value=datetime(2023,1,1).date())
endDatePicker = pn.widgets.DatePicker(name="End Date", value=datetime(2023,6,1).date())
frequencyFilter = pn.widgets.Select(name='Sampling Frequency', value='W', options=['B', 'W', 'BM', 'BQ', 'BA'])
nameFilter = pn.widgets.AutocompleteInput(name='Name Search', value='', restrict=False)
paramBox = pn.WidgetBox(startDatePicker, endDatePicker, frequencyFilter,nameFilter, width=350, sizing_mode='stretch_height')

main = pn.Tabs(("tab1", paramBox), ("tab2", paramBox))
bootstrap = pn.template.BootstrapTemplate()
bootstrap.main.append(main)
bootstrap.header_background = "black"
bootstrap.show()
###########################

I hope if I change the input, values at tab1 and tab2 will change together. But it only works when I change the input at tab1, and not work when I change tab2.

**Comment by philippjfr** [comment] 2023-06-09 10:38
Hard to find I know but this is a duplicate of https://github.com/holoviz/panel/issues/552

Sadly this is a fairly difficult problem to solve because of a very early architectural decision.

**Closed by philippjfr** 2023-06-09 10:38 UTC
