### ISSUE TITLE
Slow Jupyter lab response following Panel 0.13 installation

### ISSUE THREAD

**Issue by ItayKishon** [holoviz/panel#3531] opened 2022-05-17 14:25 UTC
#### ALL software version info
Windows 10 Business, 10.0.19044 Build 19044
Python 3.9.12
Conda 4.12.0
jupyterlab 3.4.2
panel 0.13.0
(and various others; see requirements.txt below)

#### Description of expected behavior and the observed behavior
Following installation of Panel 0.13.0, Jupyter lab becomes very slow to respond. This can be seen in various operations, e.g. cell evaluation, autocompletion, or interactive widget response. Operation which are normally instantaneous (e.g. evaluating `a=5`) can take several seconds (2 up to 5) to complete.
Note that this is *without importing anything*, specifically not even Panel.

Trying to narrow down the origin of the problem, it seems that previous versions of Panel do not exhibit this behavior. Specifically, I've downgraded to Panel=0.12.6 or 0.12.7, and everything goes back to normal.

#### Complete, minimal, self-contained example code that reproduces the issue
Creating a new minimal env:
```
conda create --name Panel_test_0 python=3.9 jupyterlab panel
```
yields the following _slow_ environment - [requirements[Panel_0.13.0].txt](https://github.com/holoviz/panel/files/8709022/requirements.Panel_0.13.0.txt)

This is fixed by downgrading to Panel=0.12:
```
conda install panel=0.12
```
which yields a normal-response environment - [requirements[Panel_0.12.6].txt](https://github.com/holoviz/panel/files/8709033/requirements.Panel_0.12.6.txt)

(checked with 0.12.7, which produces the same results as 0.12.6)

#### Stack traceback and/or browser JavaScript console output
N/A

#### Screenshots or screencasts of the bug in action
(I can added if needed)

**Comment by philippjfr** [comment] 2022-05-17 14:59
Thanks for the issue. I'm a little bit skeptical because I (and multiple devs I know) use JupyterLab daily with latest Panel installed and experience no such slowdown. Can you provide some more background? Is there anything non-standard about your environment? Are you running it locally?

**Comment by jbednar** [comment] 2022-05-17 15:41
Hmm; wonder if it's somehow Panel + JupyterLab + Windows 10?  Any other Windows 10 users happily using JupyterLab + Panel and not noticing this issue?

**Comment by philippjfr** [comment] 2022-05-17 15:43
Only thing I can imagine is that the Jupyter serverextension which gets activated automatically in 0.13 is slowing things down. As an experiment could you maybe try to install the older version (0.12.4) and then run:

```python
jupyter serverextension enable panel.io.jupyter_server_extension
```

**Comment by philippjfr** [comment] 2022-05-17 15:44
Oh also could you both report your tornado versions.

**Comment by ItayKishon-Vayyar** [comment] 2022-05-17 16:30
Tornado version: 6.1
(in both scenarios; nothing is downgraded when going from 0.13 to 0.12, apart from the explicit Panel).

Re. _panel.io.jupyter_server_extension_: it makes no difference.
(I initially tried to enable that for 0.12.6, which - as I understand - was not yet supported? In 0.12.7 I was able to enable it, and it made no difference. I.e. - Jupyter responds swiftly, as it should.)

**Comment by xavArtley** [comment] 2022-05-18 11:40
Same tornado version

**Comment by philippjfr** [comment] 2022-05-18 16:09
I'm totally guessing at the cause of this but could you try if there's any change with https://github.com/holoviz/panel/pull/3534.

**Comment by ItayKishon-Vayyar** [comment] 2022-05-19 06:01
I'm afraid #3534 doesn't fix it.

To make sure I was building the project correctly, I compared 3 versions: the potential fix, latest tag (v0.13.1a7) and the previous release (v0.12.7).

I've also recorded short videos demonstrating the problem. In each one, I evaluate the first cell (note the time it takes), and in the 2nd cell I press TAB _immediately_ after the letter `a`. You can see that only v0.12 is responding swiftly.

https://user-images.githubusercontent.com/68048422/169220085-129e6105-fec8-4080-ac26-82b15d747cab.mp4

https://user-images.githubusercontent.com/68048422/169220105-eb0574d5-db76-4416-afe5-cd0dd5860dc1.mp4

https://user-images.githubusercontent.com/68048422/169220114-100ba952-3600-4493-a492-145b97685061.mp4

**Comment by xavArtley** [comment] 2022-05-19 08:59
Don't know if it's related or if I made a mistake but the preview does not work for me:
![image](https://user-images.githubusercontent.com/18531147/169255380-5348f65e-b9c7-49d4-a036-f0b2b02163a2.png)


```cmd
[E 2022-05-19 10:55:10.517 ServerApp] 500 GET /panel-preview/render/Untitled1.ipynb (::1) 190.84ms referer=http://localhost:8888/panel-preview/render/Untitled1.ipynb
[I 2022-05-19 10:55:13.389 ServerApp] Saving file at /Untitled1.ipynb
[E 2022-05-19 10:55:13.689 ServerApp] Uncaught exception GET /panel-preview/render/Untitled1.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/panel-preview/render/Untitled1.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "D:\CIVA_RP\CIVA_SIE\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\tornado\web.py", line 1704, in _execute   
        result = await result
      File "D:\CIVA_RP\CIVA_SIE\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\io\jupyter_server_extension.py", line 116, in get
        page = server_html_page_for_session(
      File "D:\CIVA_RP\CIVA_SIE\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\embed\server.py", line 255, in server_html_page_for_session
        bundle = bundle_for_objs_and_resources(None, resources)
      File "D:\CIVA_RP\CIVA_SIE\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\embed\bundle.py", line 211, in bundle_for_objs_and_resources
        js_files.extend(js_resources.js_files)
      File "D:\CIVA_RP\CIVA_SIE\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\io\resources.py", line 299, in js_files
        dist_dir = self.dist_dir
      File "D:\CIVA_RP\CIVA_SIE\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\io\resources.py", line 259, in dist_dir
        if self.absolute:
    AttributeError: 'Resources' object has no attribute 'absolute'
[E 2022-05-19 10:55:13.694 ServerApp] {
      "Host": "localhost:8888",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Referer": "http://localhost:8888/panel-preview/render/Untitled1.ipynb",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36"    }
[E 2022-05-19 10:55:13.696 ServerApp] 500 GET /panel-preview/render/Untitled1.ipynb (::1) 196.01ms referer=http://localhost:8888/panel-preview/render/Untitled1.ipynb

```

**Comment by ItayKishon-Vayyar** [comment] 2022-05-19 09:09
> Don't know if it's related or if I made a mistake but the preview does not work for me: ![image](https://user-images.githubusercontent.com/18531147/169255380-5348f65e-b9c7-49d4-a036-f0b2b02163a2.png)
> 
> ```batchfile
> [E 2022-05-19 10:55:10.517 ServerApp] 500 GET /panel-preview/render/Untitled1.ipynb (::1) 190.84ms referer=http://localhost:8888/panel-preview/render/Untitled1.ipynb
> [I 2022-05-19 10:55:13.389 ServerApp] Saving file at /Untitled1.ipynb
> [E 2022-05-19 10:55:13.689 ServerApp] Uncaught exception GET /panel-preview/render/Untitled1.ipynb (::1)
>     HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/panel-preview/render/Untitled1.ipynb', version='HTTP/1.1', remote_ip='::1')
>     Traceback (most recent call last):
>       File "D:\CIVA_RP\CIVA_SIE\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\tornado\web.py", line 1704, in _execute   
>         result = await result
>       File "D:\CIVA_RP\CIVA_SIE\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\io\jupyter_server_extension.py", line 116, in get
>         page = server_html_page_for_session(
>       File "D:\CIVA_RP\CIVA_SIE\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\embed\server.py", line 255, in server_html_page_for_session
>         bundle = bundle_for_objs_and_resources(None, resources)
>       File "D:\CIVA_RP\CIVA_SIE\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\embed\bundle.py", line 211, in bundle_for_objs_and_resources
>         js_files.extend(js_resources.js_files)
>       File "D:\CIVA_RP\CIVA_SIE\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\io\resources.py", line 299, in js_files
>         dist_dir = self.dist_dir
>       File "D:\CIVA_RP\CIVA_SIE\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\io\resources.py", line 259, in dist_dir
>         if self.absolute:
>     AttributeError: 'Resources' object has no attribute 'absolute'
> [E 2022-05-19 10:55:13.694 ServerApp] {
>       "Host": "localhost:8888",
>       "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
>       "Referer": "http://localhost:8888/panel-preview/render/Untitled1.ipynb",
>       "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36"    }
> [E 2022-05-19 10:55:13.696 ServerApp] 500 GET /panel-preview/render/Untitled1.ipynb (::1) 196.01ms referer=http://localhost:8888/panel-preview/render/Untitled1.ipynb
> ```

@xavArtley  - I'm not sure, but I've stumbled upon this exact problem, and I believe it has already been fixed (not yet released): #3442
Moreover - as that fix has been merged (AFAIK), and I've tested the latest master, I would guess it's not related to the slowdown issue.

**Comment by xavArtley** [comment] 2022-05-19 09:29
Other experiment if I launch classic notebook from command line I have no slow down
However If I launch classic notebook from the `help` menu of jupyter lab I have the slow down

**Comment by philippjfr** [comment] 2022-05-19 13:28
So the change in #3534 actually had no effect at all, will get another PR up which hopefully will have the effect that I originally intended.

**Comment by philippjfr** [comment] 2022-05-20 08:47
I'm having a problem reproducing this. When I install 0.13.0 from pip or conda I see the slowdown but if I do a develop install locally I don't. How were you guys installing from the branch?

**Comment by xavArtley** [comment] 2022-05-20 08:58
I don't use a developpement version. I only use pip version.

**Comment by ItayKishon** [comment] 2022-05-20 09:07
My former results are from a plain `python setup.py install`.
I'm now setting up a dev environment (per https://panel.holoviz.org/developer_guide/index.html), to see if this disappears when on dev.

**Comment by philippjfr** [comment] 2022-05-20 09:19
So git bisect does blame: Patch asyncio event loop policy on windows (#3339), which means my initial guess was correct, just the fix wasn't right. This does confuse me though because according to https://github.com/jupyter/notebook/pull/5907/files the WindowsProactorEventLoopPolicy should  be fine for tornado>=6.1 and python>=3.8.

**Comment by philippjfr** [comment] 2022-05-20 09:23
Nevermind, reading that PR, it was actually reverted because:

> Looking back at tornado docs, I think we should still be using the selector loop all the time. Performance will be better, as ~everything we do is built add/remove_reader, which are slower when proactor is used do to the extra thread.

So I'll have to find a way to detect properly if we are running in Jupyter and not apply that patch.

**Comment by philippjfr** [comment] 2022-05-20 09:34
Fixed in https://github.com/holoviz/panel/pull/3537

**Comment by ItayKishon** [comment] 2022-05-20 09:44
Hurray!
#3537 does indeed solve that.

On that note - although I've just recently started using Panel, I find it extremely valuable & powerful. Thank you, and all those involved, for this great project.

**Closed** 2022-05-20 09:57 UTC

**Comment by philippjfr** [comment] 2022-05-20 11:04
Thanks for the kind words and glad we could figure this out. Will release Panel 0.13.1 later today.
