### ISSUE TITLE
AttributeError: 'Map' object has no attribute 'widgets'

### ISSUE THREAD

**Issue by bilgetutak** [holoviz/panel#3790] opened 2022-08-29 12:12 UTC
Hi,

After the most recent upgrade of ipyleaflet/ipywidgets I started to get 

`
AttributeError: 'Map' object has no attribute 'widgets'
`

Probably something new in them broke it. No information in panel serve debug log
Thanks.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
python                    3.7.12
panel                     0.13.1
ipyleaflet                0.17.1
ipywidgets                8.0.1
ipywidgets_bokeh          1.2.1
#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
from ipyleaflet import Map, Rectangle

pn.extension('ipywidgets')
m = Map(center=(39.5, 31), zoom_snap=0.25, zoom_delta=0.25, zoom=5.5)
ACCENT_COLOR = pn.template.FastListTemplate.accent_base_color
template = pn.template.FastListTemplate(
    site="Map", title="Map",
    sidebar=[],
    main=[m]
).servable();
```

#### Stack traceback and/or browser JavaScript console output
AttributeError: 'Map' object has no attribute 'widgets'
Traceback (most recent call last):
  File "~/anaconda3/envs/panel_test/lib/python3.7/site-packages/bokeh/application/handlers/code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "interaction.py", line 25, in <module>
    main=[m]
  File "/home/user/anaconda3/envs/panel_test/lib/python3.7/site-packages/panel/viewable.py", line 374, in servable
    self.server_doc(title=title, location=location) # type: ignore
  File "/home/user/anaconda3/envs/panel_test/lib/python3.7/site-packages/panel/template/base.py", line 332, in server_doc
    return self._init_doc(doc, title=title, location=location)
  File "/home/user/anaconda3/envs/panel_test/lib/python3.7/site-packages/panel/template/base.py", line 553, in _init_doc
    doc = super()._init_doc(doc, comm, title, notebook, location)
  File "/home/user/anaconda3/envs/panel_test/lib/python3.7/site-packages/panel/template/base.py", line 188, in _init_doc
    model = obj.get_root(doc, comm, preprocess=False)
  File "/home/user/anaconda3/envs/panel_test/lib/python3.7/site-packages/panel/pane/base.py", line 314, in get_root
    root = self.layout._get_model(doc, comm=comm)
  File "/home/user/anaconda3/envs/panel_test/lib/python3.7/site-packages/panel/layout/base.py", line 146, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/user/anaconda3/envs/panel_test/lib/python3.7/site-packages/panel/layout/base.py", line 131, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/user/anaconda3/envs/panel_test/lib/python3.7/site-packages/panel/pane/ipywidget.py", line 60, in _get_model
    model = self._get_ipywidget(self.object, doc, root, comm, **kwargs)
  File "/home/user/anaconda3/envs/panel_test/lib/python3.7/site-packages/panel/pane/ipywidget.py", line 49, in _get_ipywidget
    for w in obj.widgets.values():
AttributeError: 'Map' object has no attribute 'widgets'

**Comment by Hoxbro** [comment] 2022-08-29 12:14
Duplicate of #3778.

For now, downgrade `ipywidgets` to version 7.0

**Closed by Hoxbro** 2022-08-29 12:14 UTC
