### ISSUE TITLE
IPysheet comms not working if added dynamically

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2633] opened 2021-08-13 15:08 UTC
Panel: 0.12.1
Ipywidgets: 7.6.3
IPysheet: 0.4.4
IPykernel: 5.5.5
jupyter-bokeh: 3.0.2
ipywidgets-bokeh: 1.0.2

For my "Introduction to Panel" I dynamically add/ remove "components" via a `RadioButtonGroup`. One example I have is for IPywidgets. And I notice the example with IPysheets does not work if it is not the "first" component I show. I.e. added when the app is loaded.

If I serve the code below and drag the slider I would expect the value in the ipysheet to update. But it does not.

https://user-images.githubusercontent.com/42288570/129378059-bbe0ebe7-c2b1-4c27-a7b1-ff04a2794242.mp4

```python
import ipysheet
import ipywidgets as ipw
import panel as pn

pn.extension("ipywidgets", sizing_mode="stretch_width")

def ipywidgets_example():
    return ipw.DatePicker(description='Date')

def ipysheet_example():
    slider = pn.widgets.FloatSlider(value=10, start=0, end=100)
    sheet = ipysheet.sheet()
    cell = ipysheet.cell(2,2, 10., read_only=True, background_color="whitesmoke")

    @pn.depends(slider, watch=True)
    def calculate(a):
        cell.value = a
        print("update", cell.value)

    return pn.Column(slider, sheet)

components = {
    "IPYWIDGETS": ipywidgets_example(),
    "IPYSHEET": ipysheet_example(),
}

def show(component):
    component = components[component]
    return component

select = pn.widgets.RadioButtonGroup(options=list(components.keys()))
show = pn.bind(show, component=select)

pn.template.FastListTemplate(
    main=[pn.Column(select,show)],
).servable()
```

**Comment by MarcSkovMadsen** [comment] 2021-08-13 15:11
If I change the order of the components to

```python
components = {
    "IPYSHEET": ipysheet_example(),
    "IPYWIDGETS": ipywidgets_example(),
}
```

it works initially. But if I navigate to the second component and back it no longer works.

https://user-images.githubusercontent.com/42288570/129379290-e370d17b-afcc-409c-85c7-49b82f15df88.mp4

```python
import ipysheet
import ipywidgets as ipw
import panel as pn

pn.extension("ipywidgets", sizing_mode="stretch_width")

def ipywidgets_example():
    return ipw.DatePicker(description='Date')

def ipysheet_example():
    slider = pn.widgets.FloatSlider(value=10, start=0, end=100)
    sheet = ipysheet.sheet()
    cell = ipysheet.cell(2,2, 10., read_only=True, background_color="whitesmoke")

    @pn.depends(slider, watch=True)
    def calculate(a):
        cell.value = a
        print("update", cell.value)

    return pn.Column(slider, sheet)

components = {
    "IPYSHEET": ipysheet_example(),
    "IPYWIDGETS": ipywidgets_example(),
}

def show(component):
    component = components[component]
    return component

select = pn.widgets.RadioButtonGroup(options=list(components.keys()))
show = pn.bind(show, component=select)

pn.template.FastListTemplate(
    main=[pn.Column(select,show)],
).servable()
```

**Comment by MarcSkovMadsen** [comment] 2021-08-13 15:16
I can see that when I navigate to the second component (no matter the order of components) there is a **Wrong widget protocol version: received protocol version '', but was expecting major version '2'.**

![image](https://user-images.githubusercontent.com/42288570/129380881-4b4df2a2-cc8d-4db4-aaa7-e9a64ef9fbb9.png)

I don't know if this is the cause or a second error.

**Comment by philippjfr** [comment] 2022-04-01 16:17
ipysheet still has not published a bundle to npm after about a year of prodding so I'll consider it unmaintained and close this issue. There's also the ipywidgets_bokeh issue which is probably the cause of this.

**Closed by philippjfr** 2022-04-01 16:17 UTC
Labels: type: feature
