### ISSUE TITLE
Panel Tabulator with Voila doesn't store user edits

### ISSUE THREAD

**Issue by obrown06** [holoviz/panel#6731] opened 2024-04-15 14:07 UTC
Example code:
```
import pandas as pd
import panel as pn
from bokeh.models.widgets.tables import NumberEditor
pn.extension('tabulator')
out = widgets.Output()
test_df = pd.DataFrame(columns=[
        "test_column_name",
    ])
test_df.loc[0] = [1]

test_df_widget = pn.widgets.Tabulator(test_df, editors={
    "test_column_name": NumberEditor(),
})

test_button = widgets.Button(
    description="Compare",
)

def test_on_click(b):
    curr_df = test_df_widget.value
    with out:
        display(curr_df.iloc[0]["test_column_name"])
test_button.on_click(test_on_click)

with out:
    display(test_df_widget, test_button)
out
```

Running this code in a voila app, we see a table displayed with a value of "1" in row 1, column "test_column_name".

![image](https://github.com/holoviz/panel/assets/23639325/2b8d8677-7071-4760-9476-1b2cb77e0a58)

When I edit the cell (e.g., to contain 432), we see the new value:

![image](https://github.com/holoviz/panel/assets/23639325/f06dd920-d2df-4a74-9f48-82eec51b7dfd)

But when the button is pressed, the triggered callback still sees the original value:

![image](https://github.com/holoviz/panel/assets/23639325/8e5c1634-0470-480f-8893-54c1a1f69071)

Relevant versions:

```
panel                     1.4.1
voila                     0.5.6
ipywidgets                8.1.2
ipywidgets_bokeh          1.6.0
jupyter_bokeh             4.0.1
```

**Comment by Kalandoros** [comment] 2024-04-20 11:28
I can confirm the issue which has been also repoerted previuosly (see [https://github.com/holoviz/panel/issues/3963)](https://github.com/holoviz/panel/issues/3963)
It has been reported also in the voila repositorysince I wasn't sure where theorign of the bug is coming from (whether Panel or Voila) ([https://github.com/voila-dashboards/voila/issues/1435](https://github.com/holoviz/panel/issues/3963)).

**Comment by obrown06** [comment] 2024-04-23 22:51
Any thoughts here? Or suggested workarounds?

**Comment by philippjfr** [comment] 2024-04-24 06:41
Could you try upgrading to jupyter_bokeh 4.0.4?

**Comment by Kalandoros** [comment] 2024-04-24 14:04
I tested it with jupyter_bokeh 4.0.4 but the issue is still perisisting. 
It might be related to
`Failed to create module: package: @pyviz/jupyterlab_pyviz; module: ./extension`:
![image](https://github.com/voila-dashboards/voila/assets/129214458/8c7ad492-4954-4b19-8473-14e3dfe8eb7b) reported in 
 [https://github.com/voila-dashboards/voila/issues/1435](https://github.com/voila-dashboards/voila/issues/1435).

**Comment by obrown06** [comment] 2024-04-28 03:03
Any additional suggestions @philippjfr ?

**Comment by obrown06** [comment] 2024-05-02 15:12
Should we assume this bug won't be addressed in the near term @philippjfr ?

**Comment by obrown06** [comment] 2024-05-15 12:16
Any signal here would be useful @philippjfr

**Comment by philippjfr** [comment] 2024-05-15 12:18
Honestly, I don't know much about the internals of Voila, all I can say is that jupyter_bokeh works well in many other contexts (i.e. VSCode, Google Colab and in other Jupyter environments), so I'd consider this a Voila bug, not a Panel one.

**Comment by philippjfr** [comment] 2024-05-15 12:21
I'll close this as a duplicate of: https://github.com/holoviz/panel/issues/3963

**Closed by philippjfr** 2024-05-15 12:21 UTC
