### ISSUE TITLE
RadioButtonGroup has no name?

### ISSUE THREAD

**Issue by tomascsantos** [holoviz/panel#4172] opened 2022-11-30 18:53 UTC
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
`panel==0.14.1`

#### Description of expected behavior and the observed behavior
RadioButtonWidget should have a name like the other widgets

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn

w = pn.widgets.RadioButtonGroup(options=['Hello', 'World'], name='My Name')
pn.Column(w).servable()
```

#### Screenshots or screencasts of the bug in action
<img width="423" alt="image" src="https://user-images.githubusercontent.com/7690514/204883879-0b81daab-8bb5-4766-b3a5-400a492aa2fd.png">
I don't see the name rendered?

This is also visible in the reference gallery:
https://panel.holoviz.org/reference/widgets/RadioButtonGroup.html
<img width="922" alt="image" src="https://user-images.githubusercontent.com/7690514/204883984-77bca02c-6c62-4ad8-8b38-2b96fca9d48a.png">

**Comment by Hoxbro** [comment] 2022-12-01 09:24
This is a duplicate of #1313

**Closed by Hoxbro** 2022-12-01 09:24 UTC
