### ISSUE TITLE
[DOC] Refactor notebooks in /examples/user_guide

### ISSUE THREAD

**Issue by rs2** [holoviz/panel#629] opened 2019-08-30 11:26 UTC
For instance, [/examples/user_guide/Param.ipynb](https://github.com/pyviz/panel/blob/master/examples/user_guide/Param.ipynb) needs the following:
* PEP-8
* Need to explain why [/examples/user_guide/Param.ipynb#L303](https://github.com/pyviz/panel/blame/master/examples/user_guide/Param.ipynb#L303) requires `watch=True`. The snippet works with `watch=False` in a notebook, but not in Bokeh server.
* `super(Circle, self)` call is not needed.
* The number of sides in NGon is off by one from the value on the slider once the slider is moved. 
* Old-style string formatting: py27 will soon be unsupported.

Please assign this issue to me.

**Comment by jbednar** [comment] 2019-08-31 02:07
Thanks! Some notes:

- PEP-8 wasn't written with notebooks in mind, so please be more specific -- are there particular parts of PEP-8 that could be applied to improve the clarity of Param.ipynb?
- Isn't `watch=True` required in all cases?  It ensures that the method is re-executed when the indicated parameter changes, which is what we want, right?
- Seems like the entire `__init__` method can be omitted from Circle, to me.
- Any idea what the cause is?
- Is there something to do about old-style string formatting?  We can't do anything not compatible with 2.7, fo now.

**Comment by rs2** [comment] 2019-09-03 22:23
@jbednar Somehow, `ShapeViewer` picks up the previous state of `NGon`... `¯\_(ツ)_/¯`

**Comment by jbednar** [comment] 2019-09-09 21:26
I don't think #635 addresses all the items above...

**Comment by philippjfr** [comment] 2019-09-10 08:19
This was auto-closed when I merged the PR.

**Comment by philippjfr** [comment] 2023-02-17 18:43
User guides have now been replaced with how to guides and background material.

**Closed by philippjfr** 2023-02-17 18:43 UTC
Labels: type: docs
