### ISSUE TITLE
Ipywidgets not working in Panelite

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4394] opened 2023-02-05 03:26 UTC
Panelite==0.14.3

If I run the notebook `reference/panes/IPyWidget.ipynb` I don't get any output.

![image](https://user-images.githubusercontent.com/42288570/216799830-d0eee16b-14d1-4dc5-8259-22367abd185d.png)

I don't see any errors in the browser console that I relate to this.

**Comment by MarcSkovMadsen** [comment] 2023-02-05 04:36
Another example is the Matplotlib.ipynb reference notebook

![image](https://user-images.githubusercontent.com/42288570/216801819-2d52fabc-8321-4aa9-82cd-11addc68d529.png)

**Comment by MarcSkovMadsen** [comment] 2023-02-05 05:00
Another example is the Reacton notebook

![image](https://user-images.githubusercontent.com/42288570/216802623-a11b6c2d-683f-4922-a354-2a071088dbfc.png)

**Comment by philippjfr** [comment] 2023-05-03 00:07
Duplicate of https://github.com/holoviz/panel/issues/4069

**Closed by philippjfr** 2023-05-03 00:07 UTC
Labels: type: bug, panelite
