### ISSUE TITLE
UI respond slow in notebook and panel serve

### ISSUE THREAD

**Issue by Jhsmit** [holoviz/panel#984] opened 2020-01-22 18:27 UTC
#### Software info
- Panel 0.7.0
- Bokeh 1.4.0
- Tornado 6.0.3
- Jupyter Notebook
- Mozilla Firefox
- Windows 10

#### Description of expected behavior and the observed behavior
I have a slider which I expect to update when changing the corresponding parameter. I have a for loop that prints a value which appears much faster then the slider updates. When the loop is done the slider seems to rapidly catch up.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import param
import panel as pn
import time

class Test(param.Parameterized):
    window_size = param.Integer(default=6, bounds=(1, 21))
    test = param.Integer()
    btn = param.Action(lambda self: self.do_button())
    
    @param.depends('window_size', watch=True)
    def update(self):
        self.test=self.window_size

    @param.depends("test")
    def view(self):
        return "Test: " + str(self.test)
    
    def do_button(self):
        time.sleep(0.1)
        for i in range(20):
            print(i)
            self.window_size = i + 1
            time.sleep(0.1)
    
test = Test(name='Test')
pn.Column(test.param, test.view).app()

```

In the notebook, when i dont use `.app()`, or if I use `.servable()` the problem goes away. However, when I use `.servable()` and run the notebook with ` $ panel serve example.ipynb`, I again have the same problem where the slider lags behind.

Am I doing something wrong there? Do I need to run the for loop threaded to keep the UI updating?

#### Videos of bugs and wanted behaviour
Wanted behaviour, `.servable()` in notebook:
![bandicam2020-01-2219-18-12-844](https://user-images.githubusercontent.com/7881506/72922095-b7485080-3d4c-11ea-8a3c-16b609b97b9d.gif)

Buggy behaviour, `.app()` in notebook:
![bandicam2020-01-2219-19-29-567](https://user-images.githubusercontent.com/7881506/72922175-de9f1d80-3d4c-11ea-93d3-f078701526e4.gif)

Buggy behaviour, `.servable()` with `panel server`:
![bandicam2020-01-2219-20-11-126](https://user-images.githubusercontent.com/7881506/72922342-2e7de480-3d4d-11ea-9668-8c034fea9791.gif)

**Comment by philippjfr** [comment] 2020-01-22 18:29
Thanks for the issue, afaik this is a duplicate of https://github.com/holoviz/panel/issues/860, which has been fixed.

**Closed by philippjfr** 2020-01-22 18:29 UTC
