### ISSUE TITLE
Slider squeezed together in vertical orientation

### ISSUE THREAD

**Issue by matsvandecavey** [holoviz/panel#1958] opened 2021-02-02 21:32 UTC
Using the `orientation='vertical` argument doesn't give the desired output: the slider is shown, but seems squeezed. Changing e.g. `height=300` or `width=300` is not solving the problem.
Any ideas?

panel version `0.10.2`

```python
import panel as pn
pn.extension()

vert = pn.widgets.IntSlider(name='vertical ',end=10,orientation='vertical')
hor = pn.widgets.IntSlider(name='horizontal ',end=10)
pn.Row(vert,hor)
```
![image](https://user-images.githubusercontent.com/2987662/106665367-7eb99480-65a6-11eb-9a0f-386449fd2faf.png)

**Comment by jbednar** [comment] 2021-02-02 21:40
I can reproduce the same behavior on panel 0.10.3, with or without a specified height.

**Comment by mattpap** [comment] 2021-02-03 00:04
ref https://github.com/bokeh/bokeh/issues/10444

**Comment by philippjfr** [comment] 2021-02-03 11:10
Thanks @matsvandecavey, I'll close since the issue will be fixed upstream in Bokeh.

**Closed by philippjfr** 2021-02-03 11:10 UTC
Labels: bokeh, type: bug
