### ISSUE TITLE
Param does not include name of parameter when using CheckBoxGroup

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2938] opened 2021-11-21 16:10 UTC
Panel: 0.12.4

I would expect to see the name `Accept` of the parameter shown

![image](https://user-images.githubusercontent.com/42288570/142769738-24a2266c-6680-4e20-b190-f8a8f508c677.png)

```python
import panel as pn
import param


class MyElement(param.Parameterized):
    accept = param.ListSelector(default=["png", "jpg"], objects=["png", "jpg"])


element = MyElement(name="My Element")
pn.Param(
    element,
    parameters=["accept"],
    widgets={"accept": {"widget_type": pn.widgets.CheckBoxGroup, "inline": True}},
).servable()
```

**Comment by MarcSkovMadsen** [comment] 2021-11-21 16:12
It's the same problem if you change to a `CheckButtonGroup`.

**Comment by philippjfr** [comment] 2021-11-22 10:54
Duplicate of https://github.com/holoviz/panel/issues/1313 no?

**Closed by philippjfr** 2021-11-22 10:54 UTC
Labels: type: bug
