### ISSUE TITLE
jupyterlab's "Create New View for Output" does not render panel objects

### ISSUE THREAD

**Issue by pnsvk** [holoviz/panel#1940] opened 2021-01-25 03:10 UTC
Package Version: 
panel==0.10.2
jupyterlab==2.2.9
@pyviz/jupyterlab_pyviz==0.7.6

Can you please kindly help with, any workarounds for this issue ?

![CCB53EB5-A8A1-4B7E-AA02-E64BF5BA02D5_1_105_c](https://user-images.githubusercontent.com/30823233/105656659-b6f70e00-5ee8-11eb-8bef-d4969abbb115.jpeg)

In this above screenshot, the "Create New View for Output" of cell: 80, does show up an OuptutView (at the bottom), but there is nothing seen in the Output View.. 
It only renders the previously set image (colored dices png) under the newly set image in the same output cell: 80.

**Comment by MarcSkovMadsen** [comment] 2021-02-01 16:30
I reproduced the issue with 

- Jupyterlab: 3.0.6
- 0.10.3

I've assigned it the bug label. But I don't know if this has been working or is expected to work.

**Comment by philippjfr** [comment] 2021-02-02 01:14
Thanks @pnsvk and @MarcSkovMadsen. This is a known issue and you can find more discussion here: https://github.com/holoviz/pyviz_comms/issues/3. I'll close since there is more detail in the other issue.

**Closed by philippjfr** 2021-02-02 01:14 UTC
Labels: type: bug
