### ISSUE TITLE
Built-in support to open/close template sidebar

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#7001] opened 2024-07-18 19:30 UTC
From https://discourse.holoviz.org/t/programatically-dynamically-hiding-template-sidebar/1605

```python
import panel as pn

html = pn.pane.HTML("")
button_open = pn.widgets.Button(name="openNav")
button_close = pn.widgets.Button(name="closeNav")

def open(event):
    html.object = f""" <script> openNav(); </script>"""
button_open.on_click(open)

def close(event):
    html.object = f""" <script> closeNav(); </script>"""
button_close.on_click(close)

vanilla = pn.template.FastListTemplate(title='toogle_nav')
vanilla.sidebar.append(html)
vanilla.main.append(button_open)
vanilla.main.append(button_close)

pn.serve(vanilla)
```

**Comment by philippjfr** [comment] 2024-07-19 09:28
Duplicate of https://github.com/holoviz/panel/issues/2557. Closing.

**Closed by philippjfr** 2024-07-19 09:28 UTC
Labels: duplicate
