### ISSUE TITLE
dynamic option on Tabs 

### ISSUE THREAD

**Issue by jbogaardt** [holoviz/panel#2131] opened 2021-03-30 18:53 UTC
#### Is your feature request related to a problem? Please describe.
The current `dynamic` attribute on `pn.Tabs` seems to be concerned with server-client communication.  However, there are situations where each of the individual tabs of a `pn.Tabs` instance has some computationally intensive calculations for the server.  When each of these tabs depend on an app-wide/global widget, all reactive calculations occur regardless of whether the tab is active or not.  The problem here is that the server gets bogged down with calculations that the end user doesn't necessarily care about.

#### Describe the solution you'd like
Being able to limit the reactive callbacks only to the tab that is currently active or upon activation of a tab should eliminate a lot of wasteful computation in very complex apps.

#### Describe alternatives you've considered
Alternatives were sought through this [discourse discussion](https://discourse.holoviz.org/t/inactive-tab-computes-when-dynamic-true/2047) and required more advanced/unorthodox approaches to making panel `Tabs` more efficient.

**Comment by philippjfr** [comment] 2021-06-28 12:52
Sorry I never replied here, this issue is a duplicate of https://github.com/holoviz/panel/issues/1933 so I'll close.

**Closed by philippjfr** 2021-06-28 12:52 UTC
