### ISSUE TITLE
Panel objects no longer render in jupyter notebook with conda-forge version 0.9.5

### ISSUE THREAD

**Issue by pybokeh** [holoviz/panel#1237] opened 2020-04-07 02:59 UTC
I am on Windows 10 machine with Miniconda3 Python distribution installed.  Was using version 0.9.3, but after upgrading to version 0.9.5, the Panel object no longer renders in the notebook.  I just get a blank output.

EDIT: I looked at the console output that I launched Jupyter Lab from and see no error messages.  I've downgraded back to version 0.9.3 and Panel objects are rendering fine as before.  Out of curiosity, I installed version 0.9.5 via pip instead of conda and Panel objects render fine also.

**Comment by philippjfr** [comment] 2020-04-07 03:19
It seems to be the conda-forge build that's broken, see #1233 and #1235. I'll try to fix the build asap, just haven't quite figured out what's going wrong yet.

**Comment by mattpap** [comment] 2020-04-07 09:11
Closing as a duplicate of issue #1233.

**Closed by mattpap** 2020-04-07 09:11 UTC
