### ISSUE TITLE
Cannot set `configuration` thru `Tabulator.from_param`

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#5493] opened 2023-09-08 17:18 UTC
Results in

```python
import param
import panel as pn
import pandas as pd

pn.extension()


class Test(param.Parameterized):
    df = param.DataFrame()

    def __init__(self, **params):
        super().__init__(**params)
        self.tabulator = pn.widgets.Tabulator.from_param(
            self.param.df,
            configuration={"clipboard": True, "clipboardPasteAction": "replace"},
        )


Test(df=pd.DataFrame({"x": [0, 1, 2], "y": [3, 4, 5]})).tabulator.show()
```

```
WARNING:param.Test: Param pane was given unknown keyword argument(s) for 'df' parameter with a widget of type <class 'panel.widgets.tables.Tabulator'>. The following keyword arguments could not be applied: 'configuration'.
Launching server at http://localhost:57344/
```

**Comment by Hoxbro** [comment] 2023-09-09 12:29
Duplicate of https://github.com/holoviz/panel/issues/4933 

Some discussion about enabling it here https://github.com/holoviz/panel/pull/4935, and implementation of it https://github.com/holoviz/panel/pull/4959.

**Closed** 2023-09-11 13:14 UTC
Labels: TRIAGE
