### ISSUE TITLE
Wrong `selected_dataframe` when a sorter is applied

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#3664] opened 2022-06-30 10:05 UTC
When a Tabulator widget is sorted and a selection is made, the `selected_dataframe` returned is not the actual selected dataframe.

**Comment by erinatframe** [comment] 2022-08-08 17:05
this seems to have been introduced in 0.13.1

**Comment by maximlt** [comment] 2022-08-08 17:06
Yes that might well be. With the addition of UI tests we're now more confident fixing this sort of issue, and making sure it's more robust.

**Comment by orangeSi** [comment] 2023-07-17 13:46
I still get the same error with ```panel v1.2.0 + python v3.11.4``` at Window10 system, it had fixed?

**Comment by MarcSkovMadsen** [comment] 2024-02-27 08:06
+1. Hit by this too.

**Comment by MarcSkovMadsen** [comment] 2024-02-27 08:29
Duplicate of #3670. Will close this one as the other one contains more valuable information about cause.

**Closed by MarcSkovMadsen** 2024-02-27 08:29 UTC
Labels: type: bug, component: tabulator
