### ISSUE TITLE
Not sure if bug, but pn.state.sync_busy picks up on other tab's session

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/panel#2626] opened 2021-08-10 22:45 UTC
If I have two sessions through num_procs=4 the loading spinner activates on all of them if I interact with one session

**Comment by philippjfr** [comment] 2022-02-14 01:03
Thanks for the report. I don't see how this is even possible, and I could not reproduce. Suspect you simply got assigned to the same process multiple times.

**Closed by philippjfr** 2022-02-14 01:03 UTC
Labels: type: bug
