### ISSUE TITLE
Will support for Plotly charts within Panel dashboard be added?

### ISSUE THREAD

**Issue by kez4twez** [holoviz/panel#2532] opened 2021-07-14 03:20 UTC
I recently created a dashboard with Panel that features charts made with Plotly, at the time I did not know they were not compatible, my bad.

The charts render fine but lose their interactivity and become buggy.
![Screen Shot 2021-07-14 at 1 20 04 pm](https://user-images.githubusercontent.com/68575739/125555703-94c12ed9-e15b-4fcb-b91b-aeeb60d9da2d.png)

I'm wondering whether support for Plotly charts is a planned feature or not.

kez4twez

**Comment by MarcSkovMadsen** [comment] 2021-07-14 07:12
Hi @kez4twez 

i’ve been using plotly plots a lir with Panel and they are supported https://panel.holoviz.org/reference/panes/Plotly.html#

For the community to be able to help please be more specific

- which versions are you using
- Are you in notebook or on server
- What interaktivity is lidt
- What steps to reproduce?
- please priside Minimum code reproducible example.

**Comment by philippjfr** [comment] 2021-07-14 07:16
Duplicate of https://github.com/holoviz/panel/issues/804 which was just resolved and will be fixed in 0.12

**Closed by philippjfr** 2021-07-14 07:16 UTC

**Comment by kez4twez** [comment] 2021-07-14 07:24
Ok thank you phillip.

Mark I just read the similar issue raise that Mark posted and it seems it is a common problem. But as Mark stated will be fixed in 0.12, am happy to wait until then.

Thank you for trying.
