### ISSUE TITLE
vtk colorbar broken (even in refererence example!)

### ISSUE THREAD

**Issue by srepmub** [holoviz/panel#5176] opened 2023-06-27 07:20 UTC
hi! we are running into an issue, where the whole colorbar is greyed out. turns out this is even the case for the reference examples here (at least for me using google-chrom on debian linux):

https://panel.holoviz.org/reference/panes/VTK.html

if the problem is a change in vtk.js, is there an easy work-around to perhaps specificy the version of vtk.js to use..?

**Comment by edsaac** [comment] 2023-11-01 21:23
Same here on Firefox:  

![colorbar_bug](https://github.com/holoviz/panel/assets/34405119/deb37fff-b100-4ebb-b274-7f94adb6883d)

**Comment by francesco-ballarin** [comment] 2023-11-21 10:33
I had opened #5809 which turns out to be a duplicate of this. Still, I am leaving the link here because it contains additional info that may be useful.

**Closed** 2023-11-21 15:09 UTC
Labels: type: bug
