### ISSUE TITLE
IPyWidget Reference Example not working due to IpyVolume not registered as widget module

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2192] opened 2021-04-16 15:49 UTC
I'm on the current master branch (copied to the `binder` branch). When running the IPyWidget.ipynb notebook it fails

```bash
IPyWidget.ipynb:1 Uncaught (in promise) Error: Module ipyvolume, semver range ~0.5.2 is not registered as a widget module
    at x.loadClass (80.9f7417d8d295ae62fff4.js:2)
    at x.<anonymous> (80.9f7417d8d295ae62fff4.js:2)
    at 80.9f7417d8d295ae62fff4.js:2
    at Object.next (80.9f7417d8d295ae62fff4.js:2)
    at 80.9f7417d8d295ae62fff4.js:2
    at new Promise (<anonymous>)
    at S (80.9f7417d8d295ae62fff4.js:2)
    at x.e._make_model (80.9f7417d8d295ae62fff4.js:2)
    at x.<anonymous> (80.9f7417d8d295ae62fff4.js:2)
    at 80.9f7417d8d295ae62fff4.js:2
    at Object.next (80.9f7417d8d295ae62fff4.js:2)
    at 80.9f7417d8d295ae62fff4.js:2
    at new Promise (<anonymous>)
    at S (80.9f7417d8d295ae62fff4.js:2)
    at x.e.new_model (80.9f7417d8d295ae62fff4.js:2)
    at 80.9f7417d8d295ae62fff4.js:2
```

![image](https://user-images.githubusercontent.com/42288570/115050501-1b1fe180-9edc-11eb-9e88-e80a8c1b68b9.png)

**Comment by philippjfr** [comment] 2021-04-16 16:05
Suspect I need to update it for compatibility with JLab>=3.0

**Comment by meverson86** [comment] 2021-05-22 22:31
This could be related but I also am not getting any ipywidget based stuff rendered in IPyWidget panes.  Interactive Matplotlib panes also do not render since ipympl is using ipywidgets under the hood. I see the following error in my console when attempting to create an IPyWidget pane.

```
Uncaught (in promise) Error: Comm is already created
    createComm http://localhost:8889/static/lab/jlab_core.64abc115a1efeec58694.js?v=64abc115a1efeec58694:2
    _create_comm http://localhost:8889/lab/extensions/@pyviz/jupyterlab_pyviz/static/80.9f7417d8d295ae62fff4.js:2
    set_state http://localhost:8889/lab/extensions/@pyviz/jupyterlab_pyviz/static/80.9f7417d8d295ae62fff4.js:2
    set_state http://localhost:8889/lab/extensions/@pyviz/jupyterlab_pyviz/static/80.9f7417d8d295ae62fff4.js:2
    promise callback*3534/C</e.prototype.set_state http://localhost:8889/lab/extensions/@pyviz/jupyterlab_pyviz/static/80.9f7417d8d295ae62fff4.js:2
    set_state http://localhost:8889/lab/extensions/@pyviz/jupyterlab_pyviz/static/979.9e0a6baebb6cfd7e3ad6.js:1
    _render http://localhost:8889/lab/tree/Untitled1.ipynb line 2 > injectedScript:1148
    render http://localhost:8889/lab/tree/Untitled1.ipynb line 2 > injectedScript:1148
    render http://localhost:8889/lab/tree/Untitled1.ipynb line 2 > injectedScript:653
    build http://localhost:8889/lab/tree/Untitled1.ipynb line 2 > injectedScript:653
    renderTo http://localhost:8889/lab/tree/Untitled1.ipynb line 2 > injectedScript:653
    f http://localhost:8889/lab/tree/Untitled1.ipynb line 2 > injectedScript:729
    add_document_standalone http://localhost:8889/lab/tree/Untitled1.ipynb line 2 > injectedScript:729
    embed_items_notebook http://localhost:8889/lab/tree/Untitled1.ipynb line 2 > injectedScript:736
    embed_document http://localhost:8889/lab/tree/Untitled1.ipynb line 2 > injectedScript:5
    <anonymous> http://localhost:8889/lab/tree/Untitled1.ipynb line 2 > injectedScript:8
    <anonymous> http://localhost:8889/lab/tree/Untitled1.ipynb line 2 > injectedScript:24
    ...
```

Currently using:
jupyterlab 3.0.14
ipywidgets 7.6.3
panel 0.11.3
ipywidgets_bokeh 1.0.2

Let me know if you need more info.

**Comment by philippjfr** [comment] 2021-06-09 16:44
Thanks for reporting this. I just tagged pyviz_comms 2.0.2 with a fix for this issue, so I'd recommend upgrading as soon as this build is out: https://github.com/holoviz/pyviz_comms/actions/runs/922436479

**Comment by philippjfr** [comment] 2021-06-14 09:01
Closing unless someone can reproduce an issue with 2.0.2.

**Closed by philippjfr** 2021-06-14 09:01 UTC
Labels: type: bug

**Comment by meverson86** [comment] 2021-06-14 14:24
I confirmed that installing 2.0.2 fixed the issue with ipywidget panes.  Thank you for all your hard work!

**Comment by MarcSkovMadsen** [comment] 2021-06-14 14:40
Thanks for providing useful input and nice feedback @meverson86 👍
