### ISSUE TITLE
Use of ipywidgets  do not render when using the panel.react template 

### ISSUE THREAD

**Issue by epifanio** [holoviz/panel#2435] opened 2021-06-25 22:30 UTC
#### ALL software version info
Installed via `pip` on system python - ubuntu 21.10

* `Python` ` v3.9`
* `panel`  `v0.11.3`
* `bokeh` `v2.3.2`
* `ipywidgets` `v7.6.3`

```python
Python 3.9.5 (default, May 11 2021, 06:26:08) 
[GCC 10.3.0] on linux
>>> panel.__version__
'0.11.3'
>>> bokeh.__version__
'2.3.2'
>>> ipywidgets.__version__
'7.6.3'
```

#### Description of expected behavior and the observed behavior
I expect to be possible to use `IPywidgets`  in a  `pn.template.ReactTemplate` 
This works fine when using `panel` without the react template system.

#### Complete, minimal, self-contained example code that reproduces the issue

The following works as expected:

```python
import panel as pn
from ipyleaflet import Map

pn.extension(comms='ipywidgets')
pn.config.sizing_mode = 'stretch_both'

center = (52.204793, 360.121558)
m = Map(center=center, zoom=15)

pn.Row(m).servable()
```

A version using `pn.template.ReactTemplate` doesn't render:

```python
import panel as pn
from ipyleaflet import Map

react = pn.template.ReactTemplate(title='React Template')

pn.extension(comms='ipywidgets')
pn.config.sizing_mode = 'stretch_both'

center = (52.204793, 360.121558)
m = Map(center=center, zoom=15)

react.main[:, :] = pn.Card(pn.Row(m), title='Sine')
react.servable();
```

#### Stack traceback and/or browser JavaScript console output
* No Stack traceback  available
* JS console log available at: https://gist.github.com/epifanio/195275ad932f3c30073e91e11223668b 
#### Screenshots or screencasts of the bug in action

* plain `panel`
![image](https://user-images.githubusercontent.com/18949/123490392-3746aa00-d614-11eb-8dc7-7c450baee13b.png)

* `panel` + `react`
![image](https://user-images.githubusercontent.com/18949/123490256-fea6d080-d613-11eb-8687-84c72f566b47.png)

**Comment by fleming79** [comment] 2021-06-26 11:36
panel-examples/reference/panes/IPyWidget.ipynb
doesn't render either

![image](https://user-images.githubusercontent.com/1474668/123511650-d8416d80-d6c5-11eb-93dd-bf754905f81b.png)

using docker: jupyter/base-notebook:python-3.9.5

**Comment by meverson86** [comment] 2021-06-26 13:13
Try upgrading pyviz_comms to 2.0.2.  This solved the IPyWidget pane issues I was having.

**Comment by fleming79** [comment] 2021-06-26 23:03
For jupyter/base-notebook:python-3.9.5  pyviz_comms is already 2.0.2. 
I also tried upgrade of pyviz_comms on WinPython 3940 distribution with no effect.

**Comment by epifanio** [comment] 2021-06-26 23:52
On linux, system python:

```
pip install -U pyviz_comms
Collecting pyviz_comms
  Downloading pyviz_comms-2.0.2-py2.py3-none-any.whl (32 kB)
Collecting param
  Downloading param-1.10.1-py2.py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 981 kB/s 
Installing collected packages: param, pyviz-comms
Successfully installed param-1.10.1 pyviz-comms-2.0.2
```

same behavior.

**Comment by fleming79** [comment] 2021-06-27 00:13
It seems `ipywidgets_bokeh` is a dependency that I hadn't installed. Installing it fixes issues for docker: jupyter/base-notebook:python-3.9.5, but still doesn't work for winpython 3940.

panel-examples/reference/panes/IPyWidget.ipynb:
![image](https://user-images.githubusercontent.com/1474668/123529020-02c81080-d730-11eb-88bc-fbf14b0dbda4.png)

**Comment by epifanio** [comment] 2021-06-27 00:19
@fleming79 , In my test, see example code on top,  `ipywidgets` and `panel` are working fine together. 
This issue is specific for the rendering of `ipywidgets` within a `panel.template.ReactTemplate`.

**Comment by fleming79** [comment] 2021-06-27 00:25
My apologies. I thought the issue was related.

**Comment by itsgifnotjiff** [comment] 2022-11-27 16:11
Just a friendly reminder that with the recent releases of `Panel` and `ipywidgets`, this issue persists. Tested with a `Material` template `ipyleaflet` as well but no luck. I really wish I could help but after reading the code I am not sure how to fix this even though I believe @Hoxbro and @jbednar suggested it is a simple dependency update for `ipywidgets` to `8.x`.

**Comment by philippjfr** [comment] 2023-05-03 00:32
Appears to be fixed with Panel 1.0rc1 and ipywidgets_bokeh 1.4.0dev3

**Comment by epifanio** [comment] 2023-05-04 09:34
@philippjfr  which versions of the libraries are you testing?

I tested the same code posted above, using the following versions:

```
In [7]: bokeh.__version__
Out[7]: '3.1.0'

In [8]: panel.__version__
Out[8]: '1.0.0rc2.post4+gd822dba4'

In [10]: ipywidgets.__version__
Out[10]: '8.0.6'

In [11]: ipyleaflet.__version__
Out[11]: '0.17.2'

In [12]: ipywidgets_bokeh.__version__
Out[12]: '1.4.0.dev3'

```
but i get the following traceback:

```
(dashboard) ➜ panel serve panel_test  
2023-05-04 10:51:34,130 Starting Bokeh server version 3.1.0 (running on Tornado 6.3)
2023-05-04 10:51:34,130 User authentication hooks NOT provided (default user enabled)
2023-05-04 10:51:34,131 Bokeh app running at: http://localhost:5006/panel_test
2023-05-04 10:51:34,131 Starting Bokeh server with process id: 54457
2023-05-04 10:51:37,629 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x7f05e76f08e0>: 'DummyComm' object has no attribute 'kernel'
File 'ipywidget.py', line 63, in _on_widget_constructed:
if widget.comm and widget.comm.target_name != 'panel-temp-comm' and isinstance(widget.comm.kernel, PanelKernel): Traceback (most recent call last):
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/bokeh/application/handlers/code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "/home/epinux/dev/panel_test/main.py", line 13, in <module>
    react.servable();
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/template/base.py", line 393, in servable
    return super().servable(title, location, area, target)
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/viewable.py", line 384, in servable
    self.server_doc(title=title, location=location) # type: ignore
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/template/base.py", line 351, in server_doc
    return self._init_doc(doc, title=title, location=location)
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/template/base.py", line 619, in _init_doc
    document = super()._init_doc(doc, comm, title, notebook, location)
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/template/base.py", line 186, in _init_doc
    model = obj.get_root(document, comm, preprocess=False)
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/layout/base.py", line 279, in get_root
    root = super().get_root(doc, comm, preprocess)
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/viewable.py", line 639, in get_root
    root = self._get_model(doc, comm=comm)
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/layout/base.py", line 164, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/layout/card.py", line 131, in _get_objects
    objects = super()._get_objects(model, old_objects, doc, root, comm)
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/layout/base.py", line 149, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/layout/base.py", line 164, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/layout/base.py", line 149, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/pane/ipywidget.py", line 72, in _get_model
    model = self._get_ipywidget(self.object, doc, root, comm, **kwargs)
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/pane/ipywidget.py", line 60, in _get_ipywidget
    _on_widget_constructed(w, doc)
  File "/home/epinux/mambaforge/envs/dashboard/lib/python3.10/site-packages/panel/io/ipywidget.py", line 63, in _on_widget_constructed
    if widget.comm and widget.comm.target_name != 'panel-temp-comm' and isinstance(widget.comm.kernel, PanelKernel):
AttributeError: 'DummyComm' object has no attribute 'kernel'

```

**Comment by philippjfr** [comment] 2023-05-04 10:16
Hmm, those versions match what I'm using exactly. Very strange.

**Comment by epifanio** [comment] 2023-05-04 17:12
@philippjfr  - I will try to mask out the .local folder from my system - just to make sure I have a clean environment - I will install from git only `panel` and `ipywidgets_bokeh` i will let conda/mamba to deal with  the other dependencies

**Comment by epifanio** [comment] 2023-05-04 17:39
I confirm the log - I created a clean env with:

`conda create -n pyviz python=3.10`

then installed main packages with:

```bash
 mamba install ipython ipykernel jupyterlab bokeh jupyter_bokeh ipyleaflet ipywidgets
```
Then, activate the environment `conda activate pyviz` and install `panel` and `ipywidgets_bokeh`, with:

```
pip install git+https://github.com/holoviz/panel        
pip install git+https://github.com/bokeh/ipywidgets_bokeh                           
```

I created a `panel_test` app with the same code as above:

```
mkdir panel_test
echo """import panel as pn
from ipyleaflet import Map
pn.extension(comms='ipywidgets')
pn.config.sizing_mode = 'stretch_both'
center = (52.204793, 360.121558)
m = Map(center=center, zoom=15)
pn.Row(m).servable()""" > panel_test/main.py
```

then run it:

```
panel server panel_test/
```

TYhe log is the following:

```
2023-05-04 19:32:02,896 Starting Bokeh server version 3.1.0 (running on Tornado 6.3)
2023-05-04 19:32:02,896 User authentication hooks NOT provided (default user enabled)
2023-05-04 19:32:02,898 Bokeh app running at: http://localhost:5006/panel_test
2023-05-04 19:32:02,898 Starting Bokeh server with process id: 64066
```

then when loading the app url, I get a blank page and the following log:

```
2023-05-04 19:32:59,600 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x7fa65cccbf40>: 'DummyComm' object has no attribute 'kernel'
File 'ipywidget.py', line 63, in _on_widget_constructed:
if widget.comm and widget.comm.target_name != 'panel-temp-comm' and isinstance(widget.comm.kernel, PanelKernel): Traceback (most recent call last):
  File "/home/epinux/mambaforge/envs/pyviz/lib/python3.10/site-packages/bokeh/application/handlers/code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "/home/epinux/panel_test/main.py", line 7, in <module>
    pn.Row(m).servable()
  File "/home/epinux/mambaforge/envs/pyviz/lib/python3.10/site-packages/panel/viewable.py", line 384, in servable
    self.server_doc(title=title, location=location) # type: ignore
  File "/home/epinux/mambaforge/envs/pyviz/lib/python3.10/site-packages/panel/viewable.py", line 995, in server_doc
    model = self.get_root(doc)
  File "/home/epinux/mambaforge/envs/pyviz/lib/python3.10/site-packages/panel/layout/base.py", line 279, in get_root
    root = super().get_root(doc, comm, preprocess)
  File "/home/epinux/mambaforge/envs/pyviz/lib/python3.10/site-packages/panel/viewable.py", line 639, in get_root
    root = self._get_model(doc, comm=comm)
  File "/home/epinux/mambaforge/envs/pyviz/lib/python3.10/site-packages/panel/layout/base.py", line 164, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/epinux/mambaforge/envs/pyviz/lib/python3.10/site-packages/panel/layout/base.py", line 149, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/epinux/mambaforge/envs/pyviz/lib/python3.10/site-packages/panel/pane/ipywidget.py", line 72, in _get_model
    model = self._get_ipywidget(self.object, doc, root, comm, **kwargs)
  File "/home/epinux/mambaforge/envs/pyviz/lib/python3.10/site-packages/panel/pane/ipywidget.py", line 60, in _get_ipywidget
    _on_widget_constructed(w, doc)
  File "/home/epinux/mambaforge/envs/pyviz/lib/python3.10/site-packages/panel/io/ipywidget.py", line 63, in _on_widget_constructed
    if widget.comm and widget.comm.target_name != 'panel-temp-comm' and isinstance(widget.comm.kernel, PanelKernel):
AttributeError: 'DummyComm' object has no attribute 'kernel'
 
2023-05-04 19:32:59,615 404 GET /static/extensions/ipywidgets_bokeh/ipywidgets_bokeh.js?v=a9e38b39089c4f46b6c79849a7521dc45198f897fd397afd4fdd50b6cc224816 (::1) 0.29ms
2023-05-04 19:32:59,670 WebSocket connection opened
2023-05-04 19:32:59,671 ServerConnection created

```
The `JS` console has the followng log:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
bokeh.min.js?v=d4a1eba0f969a1b9ce0d43946c7cc357f701ace7f693de6e710ab393d5c546733a7b463f96f9d25ba678b51e1993b83937846dd0c3247d5a7225ea09a8aa7879:183 [bokeh] setting log level to: 'info'
bokeh.min.js?v=d4a1eba0f969a1b9ce0d43946c7cc357f701ace7f693de6e710ab393d5c546733a7b463f96f9d25ba678b51e1993b83937846dd0c3247d5a7225ea09a8aa7879:226 [bokeh] Websocket connection 0 is now open
bokeh.min.js?v=d4a1eba0f969a1b9ce0d43946c7cc357f701ace7f693de6e710ab393d5c546733a7b463f96f9d25ba678b51e1993b83937846dd0c3247d5a7225ea09a8aa7879:163 Bokeh items were rendered successfully
```

**Comment by philippjfr** [comment] 2023-05-05 09:46
@epifanio The problem is the incorrect loading of ipywidgets, i.e. you should use:

```
pn.extension('ipywidgets')
```

not 

```
pn.extension(comms='ipywidgets')
```

The former loads the ipywidgets extension for Panel, the latter changes the behavior in notebook based environments. I can add handling around this that makes this clear.

**Closed** 2023-05-05 10:48 UTC
Labels: type: bug

**Comment by epifanio** [comment] 2023-05-08 07:44
Thank @philippjfr - I changed the code to the following:

```
import panel as pn
from ipyleaflet import Map
pn.extension('ipywidgets')
pn.config.sizing_mode = 'stretch_both'
center = (52.204793, 360.121558)
m = Map(center=center, zoom=15)
pn.Row(m).servable()
```

Which now doesn't trig any error, but I got a blank page with the following log in the JS console:

```
bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:225 [bokeh] Failed to load Bokeh session 7bHakRfOvzBMlICN3Bi7LP5fcQkNKp50dDJzytxariZ3: Error: could not resolve type 'ipywidgets_bokeh.widget.IPyWidget', which could be due to a widget or a custom model not being registered before first usage
o.add_document_from_session @ bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:225
await in o.add_document_from_session (async)
g @ bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:163
n.embed_items @ bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:163
await in n.embed_items (async)
embed_document @ panel_test:44
(anonymous) @ panel_test:47
(anonymous) @ panel_test:63
o.safely @ bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:234
fn @ panel_test:39
bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:163 Error rendering Bokeh items: Error: could not resolve type 'ipywidgets_bokeh.widget.IPyWidget', which could be due to a widget or a custom model not being registered before first usage
    at p.error (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:4951)
    at p._resolve_type (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:5059)
    at p._decode_object_ref (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:4782)
    at p._decode (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:1779)
    at bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:2249
    at f (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:178:450)
    at p._decode_plain_array (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:2237)
    at p._decode (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:928)
    at p._decode_plain_object (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:2340)
    at p._decode (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:1066)
    ```
I changed the call to `pn.extrension('ipywidgets')` --  Is my code correct? 
 
```python
  GNU nano 7.2                   panel_test/main.py                             
import panel as pn
pn.extension('ipywidgets')
pn.config.sizing_mode = 'stretch_both'
from ipyleaflet import Map
center = (52.204793, 360.121558)
m = Map(center=center, zoom=15)
pn.Row(m).servable()
```

does it work on your end, using `ipyleaflet` ?

**Comment by philippjfr** [comment] 2023-05-08 07:55
It does, yes.
