### ISSUE TITLE
Issue with name parameter of some widgets

### ISSUE THREAD

**Issue by rithwikjc** [holoviz/panel#1294] opened 2020-04-23 08:54 UTC
#### ALL software version info
OS: Windows 10
Python 3.6.5
pyviz              0.10.3
panel              0.9.5
jupyterlab         2.1.0

#### Description of expected behavior and the observed behavior
Some of the widgets, even though have a `name` parameter, don't display one when the widgets are rendered.
I've seen this with the following widgets:

- checkboxgroup
- checkbuttongroup
- radioboxgroup
- radiobuttongroup

Another issue that I noticed was that the `StaticText` widget- if the `value` parameter is unspecified, the widget's `name` does not get displayed. This is unfortunate, as it removes the possibility of having a bold title displayed without any value specified. However the reverse works fine, that is without a `name` if the `value` is specified it does gets displayed.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
pn.extension()
axes = ['A', 'B', 'C', 'D']
x_text = pn.widgets.StaticText(name='X-Axis') # Does not display anything
x_axis = pn.widgets.RadioButtonGroup(name='X-axis', value=axes[0:1], options=axes)
y_text = pn.widgets.StaticText(value='Y-Axis') # Works fine
y_axis = pn.widgets.RadioButtonGroup(name='Y-axis', value=axes[3:4], options=axes)
pn.Column(text, x_axis, y_axis)
```

**Comment by jbednar** [comment] 2020-04-23 18:52
I've noticed this too, and been annoyed by the inconsistency.  It's not entirely arbitrary, as the various items in each `group` do have such a label, but I'd personally vote for the name to appear as the label by default, but for the name to be able to be suppressed with an optional setting if people prefer the old behavior.

**Comment by rithwikjc** [comment] 2020-04-24 11:17
That would be the best solution I imagine. Also it would be best to have such an option across all widgets, not only making it consistent but also allowing flexibility.

I guess instead of having an optional setting/variable to control this behavior it could just be controlled by whether `name` is specified or not, i.e. making it an optional parameter.
Although it would indeed be confusing to have sliders and some other widgets that don't have a `name`, but the trade-off being not having to use another parameter to specify to control something trivial. Do you think that's a good idea?

I'll take a look at the code and see if I can make heads or tails of it, to see if I can make the required changes and put up a pull request for the changes.

**Comment by jbednar** [comment] 2020-04-24 20:49
Most objects in HoloViz tools are of type Parameterized, and Parameterized objects always have a name (even if not explicitly set).  The auto-generated names are somewhat useless (something like RadioButtonGroup000051), so starting to show the name will be a bit confusing for people who have previously never set the name.  I'd agree that setting the name to None should make it  not be shown, but I do think there should be a parameter to control it explicitly, as users could then set such a parameter once at the class level for that type (e.g. RadioButtonGroup.show_name=False) instead of having to override the auto-generated name for every instance of that class.

**Comment by philippjfr** [comment] 2021-12-08 11:17
Going to close as duplicate of https://github.com/holoviz/panel/issues/1313 since that nicely summarizes the status of labels on all the widgets.

**Closed by philippjfr** 2021-12-08 11:17 UTC
Labels: type: feature
