### ISSUE TITLE
(pn.Swipe) After/before panels unlinked when a selector is applied

### ISSUE THREAD

**Issue by ivandorte** [holoviz/panel#4839] opened 2023-05-14 13:14 UTC
panel==1.0.0rc8
bokeh>=3.1.1,<3.2.0
holoviews>=1.16.0a2

OS: Ubuntu 22.04.2 LTS, WSL 2, Windows 11
Tested in Chrome and Edge

While a was testing the Swipe layout I noticed that the after and befor panels disconnect when selecting an option from the widgets connected to it.

Image code:
https://github.com/ivandorte/eo-notebooks-apps/blob/db610539b6c1e5d84d00afbeceed8ad2a6ec3853/s2-panel-app/app.py#L252-L315

You can find the full code of the data APP here:
[s2-panel-app](https://github.com/ivandorte/eo-notebooks-apps/tree/main/s2-panel-app)

VIDEO:

https://github.com/holoviz/panel/assets/1726395/8c51b7c3-fb38-4e07-9a78-85956e72ea6c

**Comment by philippjfr** [comment] 2023-05-14 14:53
Thanks, seems unrelated to the Swipe layout and therefore like a duplicate of https://github.com/holoviz/panel/issues/4838

**Closed by philippjfr** 2023-05-14 14:53 UTC
