### ISSUE TITLE
Serve not working in clean conda enviroment

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#1250] opened 2020-04-09 14:51 UTC
#### ALL software version info
panel	0.8.5
python	3.8.2
conda	4.8.3
Windows	10

#### Description of expected behavior and the observed behavior
When I create a clean environment with conda and install panel the serve command does not work.

#### Complete, minimal, self-contained example code that reproduces the issue

Commands to recreate problem:
```
conda create -n test -y
conda activate test
conda install panel=0.9.5 -c pyviz -y 
panel serve test.py --show
```

test.py
```
import panel as pn

pn.pane.Markdown("Test").servable()
```

.condarc file
```
ssl_verify: true
channels:
  - pyviz
  - conda-forge
  - defaults
```

#### Stack traceback and/or browser JavaScript console output
![2020-04-09 16_36_38](https://user-images.githubusercontent.com/19758978/78907733-5db90d80-7a81-11ea-90a1-88a07e51aee0.png)

**Comment by philippjfr** [comment] 2020-04-09 15:19
Thanks for filing the issue, this is a duplicate of https://github.com/holoviz/panel/issues/1233. This comes down to a bug in bokeh 2.0.1, which will be fixed in 2.0.2. For now you should be able to set `BOKEH_RESOURCES=cdn` as an environment variable to fix this.

**Closed by philippjfr** 2020-04-09 15:19 UTC
